- ports/www/npm/Makefile.DragonFly
This only fixes a symptome, as it avoids username to uid lookups
via the node_modules/uid-number module. The module in question
exploits a number of bugs in nodejs (www/node) and libuv:
1. process.execPath returns "node\0test.js" instead of just "node".
This is actually a bug in the DragonFly port of libuv in function
uv_exepath(). Upstream patches send!
2. node is somehow unable to fork itself and open stdin/stdout
correctly in the child. Replacing the
node_modules/uid-number/get-uid-git.js script by an equivalent
in shell works, but would break the module checksums.
> www/npm: Fix build on DragonFly

- ports/devel/boehm-gc/dragonfly/patch-dyn_load.c
- ports/devel/boehm-gc/dragonfly/patch-tools_threadlibs.c
- ports/devel/libunistring/Makefile.DragonFly
- ports/lang/guile2/Makefile.DragonFly
with these changes even devel/autogen (5.18.4)
compiles and only have a single FAIL (date tag after "It has been AutoGen-ed")
> D1507 fix guile2

- ports/devel/tclbsd/Makefile.DragonFly
- ports/devel/yajl-tcl/Makefile.DragonFly
This should fix-up ./configure patching during build.
Patching should be invoked before do-configure target but after run-autotools one.
> D1507 fix tcl autools

- ports/java/openjdk8/Makefile.DragonFly
- ports/java/openjdk8/dragonfly/patch-jdk_make_lib_networkinglibraries.gmk
fix is slightly more complex than that for openjdk7 due to the jdk build
changes
http://lists.dragonflybsd.org/pipermail/users/2015-January/207360.html
the change to the build file was taken from here:
http://hg.openjdk.java.net/bsd-port/jdk8/jdk/rev/ffe5580b349c
so it will probably go away someday
> fixes openjdk8 networking issues on DFly4.2

- ports/games/ioquake3/Makefile.DragonFly
avoid custom pasta in unix.c
reduce OPT to -O1 for build tools
while there remove -DMAP_ANONYMOUS
rebuild list:
games/ioquake3
games/ioquake3-devel
games/ioquake3-devel-server
games/ioquake3-server
games/iourbanterror
games/iourbanterror-server
games/openarena
games/openarena-server
> Fix games/ioquake3

- ports/sysutils/conky/Makefile.DragonFly
- ports/sysutils/conky/dragonfly/patch-configure.ac.in
- ports/sysutils/conky/dragonfly/patch-src_Makefile.am
- ports/sysutils/conky/dragonfly/patch-src_Makefile.in
- ports/sysutils/conky/dragonfly/patch-src_common.c
- ports/sysutils/conky/dragonfly/patch-src_conky.h
- ports/sysutils/conky/dragonfly/patch-src_core.c
- ports/sysutils/conky/dragonfly/patch-src_dragonfly.c
- ports/sysutils/conky/dragonfly/patch-src_dragonfly.h
- ports/sysutils/conky/dragonfly/patch-src_entropy.c
- ports/sysutils/conky/dragonfly/patch-src_fs.c
- ports/sysutils/conky/dragonfly/patch-src_iconv_tools.c
- ports/sysutils/conky/dragonfly/patch-src_text_object.h
Default .conkyrc config is working.
Currently:
no disk I/O (devstat fun);
running proc count stays at 0;
six digit pid numbers get truncated to just 5 ones.
Port is very complicated due to FreeBSD patches that prevents applying few changes now.
Once those files/* get settled-in (or dropped) and if there would be interest from users
planing to submit dragonfly/* patches upstream for official support.
Would be very glad for patches and feature testing.
Happy ~/.conkyrc pimping!
p.s. port is explicitly made to be upstream-happy(note autogen.sh)
> sysutils/conky: initial port with intent to upstream it

- ports/games/freeminer/dragonfly/patch-cmake_Modules_FindGettextLib.cmake
DragonFly is a BSD.
Why NLS option is coming by default?
> games:/freeminer: fix libintl.so detection on DragonFly

- ports/graphics/luxrender/Makefile.DragonFly
- ports/graphics/openimageio/Makefile.DragonFly
- ports/graphics/openimageio/dragonfly/patch-src_libOpenImageIO_imagebufalgo_draw.cpp
- ports/graphics/openimageio/dragonfly/patch-src_libutil_ustring.cpp
- ports/graphics/openimageio/dragonfly/patch-src_make_detectplatform.mk
This hopefully brings one step closer to building graphics/blender and LuxMark (OpenCL benchmark) on DragonFly.
Includes font directory search patch in /usr/local/share/fonts.
> D1509 add openimageio

- ports/comms/libticables2/Makefile.DragonFly
- ports/comms/libticalcs2/Makefile.DragonFly
- ports/comms/tilp2/Makefile.DragonFly
- ports/devel/libtifiles2/Makefile.DragonFly
- ports/emulators/tiemu3/Makefile.DragonFly
Simple fix with regex, hard with patches.
Idea is to include dragonfly ARCH under \*-\*-\*bsd\* group.
This changes -D__LINUX__ --> -D__BSD__ (for now mostly was cosmetic).
Also prevents wrongly dumping x86_64 directly to CFLAGS (libticables2).
> D1509 fix ti group

- ports/devel/gearmand/Makefile.DragonFly
- ports/devel/gearmand/dragonfly/patch-configure
- ports/devel/gearmand/dragonfly/patch-libtest_main.cc
Tests:
FAIL: libtest/unittest
FAIL: libhostile/t/pipe
FAIL: libhostile/t/hostile_pipe
FAIL: libhostile/t/pipe2
FAIL: libhostile/t/hostile_pipe2
FAIL: tests/libgearman-1.0/client_test
====================================================
6 of 28 tests failed
(6 tests were not run)
> devel/gearmand: interesting port

- ports/x11-fm/xplore/Makefile.DragonFly
While it can compile and run
it segfaults in libXt.so when changing shelfs.
Also there are better alternatives anyway.
> x11-fm/xplore: disable build

- ports/sysutils/pax-utils/dragonfly/patch-porting.h
gmake test: (port needs bash shebangfix and gsed) for now only manual
PASS: scanelf.simple
PASS: lddtree.sh.smoke
PASS: src.typos
PASS: src.obsolete.funcs
PASS: src.bad.constants
PASS: src.obsolete.headers
PASS: src.use.xfuncs
PASS: src.style
PASS: src.space
> sysutils/pax-utils: add few extra __DragonFly__

- ports/x11-themes/qtcurve/Makefile.DragonFly
Nothing better came in mind.
First rebuild:
x11-themes/qtcurve (to fetch Makefile.DragonFly)
Only then try:
x11-themes/qtcurve-qt4
x11-themes/qtcurve-qt5
> x11-themes/qtcurve-qt45: fix std::isnan issue

- ports/games/openspades/Makefile.DragonFly
- ports/games/openspades/dragonfly/patch-Sources_AngelScript_source_as_memory.cpp
- ports/games/openspades/dragonfly/patch-Sources_ENet_unix.c
USES+= alias behaves strangely in build system thus patches
> games/openspades: cmath fix

- ports/benchmarks/fio/dragonfly/patch-Makefile
- ports/benchmarks/fio/dragonfly/patch-libfio.c
- ports/benchmarks/fio/dragonfly/patch-os_os-dragonfly.h
- ports/benchmarks/fio/dragonfly/patch-os_os.h
WARNING: and you thought dd was dangerous ;)
Adapted from os-openbsd.h, basic functionality seems to be working:
$ cat random-read-test.fio
; radon read test on ufs mount
[random-read]
rw=randread
size=2g
directory=/zzz/zrj
$ fio random-read-test.fio
fio: this platform does not support process shared mutexes, forcing use of threads. Use the 'thread' option to get rid of this warning.
random-read: (g=0): rw=randread, bs=4K-4K/4K-4K/4K-4K, ioengine=sync, iodepth=1
fio-2.1.9
Starting 1 thread
random-read: Laying out IO file(s) (1 file(s) / 2048MB)
Jobs: 1 (f=1): [r] [92.3% done] [182.5MB/0KB/0KB /s] [46.7K/0/0 iops] [eta 00m:01s]
random-read: (groupid=0, jobs=1): err= 0: pid=2: Sun Sep 20 11:20:29 2015
read : io=2048.0MB, bw=179628KB/s, iops=44906, runt= 11675msec
clat (usec): min=1, …
> benchmarks/fio: initial port

- ports/benchmarks/iozone/Makefile.DragonFly
- ports/benchmarks/iozone/dragonfly/patch-src_current_iozone.c
Use native target for build.
Fixed define typo to get O_RSYNC define.
Added missing __DragonFly__ for O_DIRECT.
$ iozone -a
Iozone: Performance Test of File I/O
Version $Revision: 3.420 $
Compiled for 64 bit mode.
Build: dragonfly
...
Run began: Mon Sep 21 18:00:17 2015
Auto Mode
Command line used: iozone -a
Output is in Kbytes/sec
Time Resolution = 0.000001 seconds.
Processor cache size set to 1024 Kbytes.
Processor cache line size set to 32 bytes.
File stride size set to 17 * record size.
random  random    bkwd   record   stride
KB  reclen   write rewrite    read    reread    read   write    read  rewrite     read   fwrite frewrite   fread  freread
64       4  253048 2467108  4564786  5283570 3541098 2379626 3057153  3057153  4018152  2662899  2923952 2379626  3958892
...
524288   16384 …
> benchmarks/iozone: fix build of dragonfly target

- ports/japanese/Wnn6-lib/diffs/pkg-plist.diff
Avoids installing libs with broken symlinks.
Also satisfies LIB_DEPEND for japanese/esecanna-module-wnn6
> japanese/Wnn6-lib: add .so.2.0 to list too

- ports/japanese/canna-server/Makefile.DragonFly
- ports/japanese/canna-server/dragonfly/patch-canna_widedef.h
Untested(many ???? chars in terminals)
Allows to build two dictonaries:
japanese/cannadic
japanese/gskk
> japanese/canna-server: allow to build safely

- ports/benchmarks/libmicro/Makefile.DragonFly
Not sure if working correctly. Had to disable few tests.
libmicro_bench output: http://sprunge.us/LTPc
> benchmarks/libmicro: add it or not?

- ports/x11-themes/qtcurve/Makefile.DragonFly
Untested.
Seems no longer needed, should unbreak qtcurve-gtk2/qtcurve-kde4 builds.
> x11-themes/qtcurve: prune isnan patch

- ports/multimedia/mpv/Makefile.DragonFly
While there disable stop_screensaver by default for now.
It causes problems with i915kms driver.
> multimedia/mpv: add options by default

- ports/x11/nxcomp/Makefile.DragonFly
Doesn't crash, should allow to build Skipped ports
> x11/nxcomp: add alias

- ports/net/netwib/Makefile.DragonFly
Builds, tools run, but couldn't figure out how to get /dev/bpf0.
> net/netwib: alias to FreeBSD sys-platform

- ports/lang/nx/Makefile.DragonFly
Regression Test Summary:
Environment: Tcl 8.6.4, OS DragonFly 4.3-DEVELOPMENT machine x86_64 threaded 1.
NSF performed 4844 tests in 45 files, success 4844, failures 0 in 10.229 seconds
Congratulations, NSF 2.0b5, NX 2.0b5, and XOTcl 2.0b5 work fine in your environment.
> lang/nx: tcl fix

- ports/x11/cool-retro-term/diffs/Makefile.diff
UNTESTED_REASON= QT5(requires dbus)
> x11/cool-retro-term: add OPSYS

- ports/databases/grass/Makefile.DragonFly
Very Very strange port, requires half of python ports.
At least it installed and grass64 launched graphical GUI.
> databases/grass: try compile

- ports/net/xisp/Makefile.DragonFly
Requires users in dialer group.
Graphical interface(xisp) starts up
> net/xisp: predefine USE_OPENSSL

- ports/graphics/libGL/diffs/Makefile.common.diff
Should be enough to build all meta ports
and don't complicate them.
(untested, nuked /usr instead of /usr/obj *FACEPALM*)
> mesa/vdpau: try quick fix

- ports/graphics/libGL/diffs/Makefile.common.diff
Missed this hunk, vdpau libs were compiled but
VDPAU="@comment" took precedence against VDPAU="" in PLIST_SUB
thus radeon vdpau libs were not packaged.
> mesa/vdpau: package radeon vdpau libs in dri

- ports/x11-drivers/xf86-input-vmmouse/dragonfly/patch-configure
Just simple configure patch to use /dev/io
Correct?
> x11-drivers/xf86-input-vmmouse: fix ioperm detect

- ports/devel/libosmocore/dragonfly/patch-include_osmocom_core_endian.h
Since osmocom/core/endian.h is installed into local
USES+= alias doesn't help and actual patch is needed.
> devel/libosmo-sccp: fix libosmo endian.h

- ports/www/dfileserver/dragonfly/patch-src_DirectoryIndexing.cxx
Missing algorithm include for sort().
Running gives:
Listening on port: 2000
> www/dfileserver: add with simple fix for sort

- ports/sysutils/bacula-server/Makefile.DragonFly
- ports/sysutils/bacula-server/dragonfly/patch-configure
Play dirty with CPPFLAGS, CFLAGS and piggy back on OpenBSD.
As for XATTR support have no idea (simply not familiar),
port should have a proper DragonFly support (if useful)
> sysutils/bacula: just a compile fix

- ports/devel/libdevq/Makefile.DragonFly
This 2nd part of patch to correctly get CARD_ID in mesa.
radeonkms before Nov 1 and i915kms are unaffected.
For now use sed to do a substitution to help
with upcoming libEGL devq additions.
While there for now activate PROGRAMS option,
to aid with debugging process (devq_lsdri).
> devel/libdevq: fix PCI detection for radeon cards

- ports/graphics/libGL/dragonfly/patch-src_mesa_drivers_dri_common_xmlconfig.c
This allows to use per application xml configs
from /usr/local/etc/drirc on DragonFly.
> graphics/dri: add missing getprogname definition

- ports/security/bro/Makefile.DragonFly
- ports/security/bro/dragonfly/patch-aux_broctl_bin_helpers_top
- ports/security/bro/dragonfly/patch-src_threading_BasicThread.cc
dumb cmake + dumb cxx
For now do not include -pedantic in CXXFLAGS,
looks like devs use smth to create runtime exception at runtime.
While there fix top(1) wrapper for DragonFly.
Since it is cmake:outsource not tested.
When running configure manually:
_# make test
[ 62%] plugins.bifs-and-scripts ... failed
[ 62%] plugins.hooks ... failed
[ 62%] plugins.api-version-mismatch ... failed
[ 62%] plugins.bifs-and-scripts-install ... failed
[ 62%] plugins.file ... failed
[ 63%] plugins.pktdumper ... failed
[ 63%] plugins.pktsrc ... failed
[ 63%] plugins.init-plugin ... failed
[ 63%] plugins.reader ... failed
[ 64%] plugins.writer ... failed
[ 65%] plugins.protocol ... failed
[ 70%] scripts.base.frameworks.input.raw.stderr ... failed
[ 70%] istate.pybroccoli ... failed
13 of 802 tests failed, 63 …
> security/bro: does something

- ports/devel/sdl2pp/Makefile.DragonFly
_# make test
Running tests...
Test project /usr/obj/dports/devel/sdl2pp/work/libSDL2pp-0.10.0
Start 1: test_pointrect
1/5 Test #1: test_pointrect ...................   Passed    0.01 sec
Start 2: test_pointrect_constexpr
2/5 Test #2: test_pointrect_constexpr .........   Passed    0.01 sec
Start 3: test_rwops
3/5 Test #3: test_rwops .......................   Passed    0.01 sec
Start 4: test_optional
4/5 Test #4: test_optional ....................   Passed    0.01 sec
Start 5: test_error
5/5 Test #5: test_error .......................   Passed    0.01 sec
100% tests passed, 0 tests failed out of 5
Total Test time (real) =   0.05 sec
> devel/sdl2pp: fix Werror+pedantic

- ports/lang/nim/Makefile.DragonFly
Use gcc on myos=freebsd.
Still full support would be better.
> lang/nim: fix build on dragonfly

- ports/sysutils/logrotate/Makefile.DragonFly
Use autoreconf and configure to "properly" build this port on DragonFly.
Upstream (FreeBSD ports) uses Makefile from tarball that's marked as "deprecated". And even files/patch-Makefile is partly obsolete, as it duplicates "ifeq" block for FreeBSD.
> Fix build of sysutils/logrotate on DragonFly.

- ports/net/3proxy/dragonfly/patch-Makefile.unix
In Makefile.unix, set variable LN unconditionally to "a linker",
so that it does not collide with settings from Mk/bsd.commands.mk.
> Fix build of net/3proxy on DragonFly.

- ports/benchmarks/interbench/dragonfly/patch-interbench.c
While it looks to be correct, haven't tested swap part
don't have swab enabled systems.
Everything else seems to be correct, if i load system externally
deviations start to be registered.
> benchmarks/interbench: add DragonFly swap handling

- ports/net-im/gloox/Makefile.DragonFly
tests:
tlsgnutls_test fails
GnuTLS error: Insufficient credentials for that request.
test 'anon client/server handshake test' failed
GnuTLS error: The specified session has been invalidated for some reason.
> net-im/gloox: fix string > cstring

- ports/multimedia/mplayer/Makefile.DragonFly
Apply the same tweak as done for mencoder in commit 3afd9f760+.
Without it, mplayer compiles fine but fails to run with error
'/lib/libc.so.8: Undefined symbol "__progname"'.
> Fix multimedia/mplayer with gold linker.

- ports/x11-fm/qtfm/Makefile.DragonFly
- ports/x11-fm/qtfm/dragonfly/patch-src_bookmarks.cpp
DragonFly is missing EVFILT_FS implementation in kqueue(2). So rather than
checking for mount events inefficiently (for example via getmntinfo(3)),
disable autoBookmarkMounts() feature for now (until there is EVFILT_FS).
> Fix build of x11-fm/qtfm on DragonFly.

- ports/graphics/devil/Makefile.DragonFly
- ports/graphics/devil/dragonfly/patch-fix-gcc50-build
While there, enable EXR format, needed for my work and it works:
$ ilur -l GrayRampsDiagonal.exr -s result.jpg -a 'iluBlurAvg(6)'
make check:
Formats that were OK: BMP DDS EXR HDR JP2 JPG PCX PNG PPM SGI TGA TIF
Failed formats:  ICO PSD
> graphics/devil: fix gcc50 build

- ports/x11-fm/qtfm/dragonfly/patch-src_bookmarks.cpp
Don't pass uninitialized variable to kevent().
Suggested by: ivadasz
> Stabilize x11-fm/qtfm.

- ports/graphics/cegui/Makefile.DragonFly
- ports/graphics/cegui/dragonfly/patch-cegui_src_System.cpp
tests(with null renderer and tests on):
Running tests...
Test project /usr/obj/dports/graphics/cegui/cegui-0.8.4
Start 1: CEGUITests
1/1 Test #1: CEGUITests .......................   Passed    0.10 sec
100% tests passed, 0 tests failed out of 1
> graphics/cegui: fix build

- ports/benchmarks/interbench/dragonfly/patch-interbench.c
vm.swap_size returns int
Thanks ivadasz!
> benchmarks/interbench: fix swap type on DragonFly

- ports/devel/godot/Makefile.DragonFly
Window working but on i915 same intel_uncore stuff
failed wait in intel_do_flush_locked()
Also depends on substitution of ${ARCH}==amd64 => x86_64
> devel/godot: add alias

- ports/games/enigma/Makefile.DragonFly
- ports/games/enigma/dragonfly/patch-lib-src__enigma-core__ecl_util.hh
- ports/games/enigma/dragonfly/patch-src__Utf8ToXML.hh
- ports/games/enigma/dragonfly/patch-src__file.hh
segfaults with png > v1.5 + name conflict with /usr/bin/enigma cypher
libpng error: error message "IDAT: invalid distance too far back" is shown
> games/enigma: mark as broken

- ports/games/cleanq3/Makefile.DragonFly
While it could compile, segfaults hard at runtime
> games/cleanq3: mark as broken

- ports/sysutils/monit/Makefile.DragonFly
- ports/sysutils/monit/dragonfly/patch-configure.ac
- ports/sysutils/monit/dragonfly/patch-libmonit-configure.ac
- ports/sysutils/monit/dragonfly/patch-libmonit-src-system-dragonfly-Link.inc
- ports/sysutils/monit/dragonfly/patch-src-device-sysdep_DRAGONFLY.c
- ports/sysutils/monit/dragonfly/patch-src-monit.h
- ports/sysutils/monit/dragonfly/patch-src-process-sysdep_DRAGONFLY.c
- ports/sysutils/monit/dragonfly/patch-src-process.c
- ports/sysutils/monit/dragonfly/patch-src-system-Link.c
Take these FreeBSD support files as a reference...
libmonit/src/system/os/freebsd/Link.inc
src/device/sysdep_FREEBSD.c
src/process/sysdep_FREEBSD.c
... copy them to DragonFly counterparts and adapt initprocesstree_sysdep()
and used_system_memory_sysdep() in the latter.
Note: optimally, we should get this included in Monit source, however DPorts
is an ideal place to test and polish it before pushing to upstream.
> Add DragonFly support to sysutils/monit.

- ports/games/wizznic/Makefile.DragonFly
remove 'inline' to build w/ gcc50 (from upstream)
https://github.com/DusteDdk/Wizznic/commit/977b5ddc46dddb7955ca471daf29b5ae360c1d3d
Puzzle game works
> games/wizznic: fix build

- ports/games/nexuiz/diffs/Makefile.diff
- ports/games/nexuiz/dragonfly/patch-sources__darkplaces__BSDmakefile
- ports/games/nexuiz/dragonfly/patch-sources__darkplaces__cd_bsd.c
- ports/games/nexuiz/dragonfly/patch-sources__darkplaces__common.h
- ports/games/nexuiz/dragonfly/patch-sources__darkplaces__makefile
- ports/games/nexuiz/dragonfly/patch-sources__darkplaces__quakedef.h
- ports/games/nexuiz/dragonfly/patch-sources__darkplaces__sys_shared.c
Darkplaces mod plays awesomelly! Both glx and sdl backends
on both radeonsi and haswell.
WARNING: size..
distfiles - single engine+data(888M) + optional(ON) map pack(108M)
package - .txz 879M
installed - 963M
> games/nexuiz: fix port

- ports/graphics/cimg/Makefile.DragonFly
This one took some time to figure out.
Some examples work, others give:
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
Looks to be xorg+mesa issue, also some missing demo images.
> graphics/cimg: fix build, by renaming CCVER

- ports/math/eigen3/dragonfly/patch-src_Core_util_Memory.h
This one biten me on blender (eigen3 redist).
Tests: (looks like there are still problems in libm)
99% tests passed, 8 tests failed out of 644
Label Time Summary:
Official       = 203.77 sec
Unsupported    =  21.29 sec
Total Test time (real) = 225.54 sec
The following tests FAILED:
552 - sparselu_3 (OTHER_FAULT)
571 - matrix_exponential_8 (OTHER_FAULT)
577 - matrix_exponential_9 (OTHER_FAULT)
579 - matrix_function_2 (OTHER_FAULT)
580 - matrix_function_3 (OTHER_FAULT)
587 - matrix_power_9 (OTHER_FAULT)
605 - openglsupport (OTHER_FAULT)
630 - levenberg_marquardt (OTHER_FAULT)
> math/eigen3: use posix_memalign

- ports/devel/p5-BSD-devstat/Makefile.DragonFly
> devel/p5-BSD-devstat: mark as ignored

- ports/sysutils/p5-BSD-Jail-Object/Makefile.DragonFly
> sysutils/p5-BSD-Jail-Object: mark as ignored

- ports/mail/p5-Mail-ClamAV/dragonfly/patch-Makefile.PL
Untested, needs /var/db/clamav database to be built for usage.
> mail/p5-Mail-ClamAV: add dragonfly

- ports/textproc/ctpp2/dragonfly/patch-include_CTPP2SysTypes.h
- ports/textproc/ctpp2/dragonfly/patch-src_functions_FnRandom.cpp
Tests: (diffs in version: v2.8.2 vs v2.8.3)
98% tests passed, 1 tests failed out of 57
Total Test time (real) =   1.30 sec
The following tests FAILED:
26 - Functions_D (Failed
> textproc/ctpp2: fix build

- ports/emulators/qemu-devel/dragonfly/patch-coroutine-ucontext.c
On DragonFly, when using swapcontext to enter a new context initialized
with makecontext all signals are left blocked in the new context. Since
qemu then uses siglongjmp (without a previously saved signal mask) to
continue in the original context, all signals are still blocked.
The most simple workaround is to just save the signal mask in the sigsetjmp
before using swapcontext to enter the new ucontext.
Without this workaround the virtual-machine isn't getting interrupted
(e.g. by the timer-interrupt) when it is running in a busy loop
(like "while true; do echo a > /dev/null; done" in the shell),
because SIGUSR1 is blocked.
> emulators/qemu-devel: Work around makecontext behaviour on DragonFly.

- ports/audio/cmus/dragonfly/patch-scripts-checks.sh
This fixes mp4v2/mp4v2.h header detection.
TUI player starts, seems to be working
> audio/cmus: fix build after new defaults

- ports/graphics/gstreamer-plugins-gl/Makefile.DragonFly
- ports/multimedia/gstreamer-plugins-good/dragonfly/patch-configure
- ports/multimedia/gstreamer-plugins-good/dragonfly/patch-sys_v4l2_gstv4l2object.h
- ports/multimedia/gstreamer-plugins/Makefile.DragonFly
- ports/multimedia/gstreamer/Makefile.DragonFly
This one is a complicated one and long I wanted to fix these properly.
Build order: (depends on master Makefiles thus has to build in separate poudriere builds)
1) multimedia/gstreamer
then
2) multimedia/gstreamer-plugins
then
3) (these can be build together)
multimedia/gstreamer-plugins-{all,annodex,bad,buzztard,bz2,core}
multimedia/gstreamer-plugins-{dts,dv,dvd,fluendo-mpegdemux,gnonlin,good}
multimedia/gstreamer-plugins-{mpeg2dec,mpeg2enc,resindvd,schrodinger}
multimedia/gstreamer-plugins-{theora,ugly,v4l2,vdpau,vp8,x264,xvid}
graphics/gstreamer-plugins-gl
This way all patching will get in order and build properly :)
> D1512 tweak gstreamer

- ports/multimedia/mkvalidator/Makefile.DragonFly
Tested, reports correct mkv files and bad ones:
ERR201: Invalid 'EncryptedBlock' for profile 'matroska v4' in Cluster at 20207
ERR201: Invalid 'EncryptedBlock' for profile 'matroska v4' in Cluster at 20207
ERR200: Missing element 'Block' in BlockGroup at 45212
ERR0C3: Unknown track #12 in Cluster at 20207 in SimpleBlock at 36152
ERR0B2: Block at 36152 is using an unknown track #12
ERR0A1: The Cluster PrevSize 12783829 at 45115 should be 14123
WRN0D0: There are 5271 bytes of void data..
So good!
> multimedia/mkvalidator: add alias

- ports/multimedia/avidemux/Makefile.DragonFly
- ports/multimedia/avidemux/dragonfly/patch-avidemux_core__ADM_core__include__ADM_default.h
This one is complicated too.
Rebuild just multimedia/avidemux first.
Then in separate run rest avidemux-{cli,plugins,qt4}
Tested, plugins now work.
> multimedia/avidemux: retweek ffmpeg inlining in cxx

- ports/x11/decurs/dragonfly/patch-src_cppstring.cc
> x11/decurs: fix va_start/va_end w/ stdarg.h

- ports/emulators/qemu-devel/diffs/Makefile.diff
- ports/emulators/qemu-devel/dragonfly/vknet-patch
Adds a vknet network backend to qemu-devel that allows utilizing the vknetd(1) userspace switch similarly to how it can already be used vor DragonFly vkernels.
can be used by adding to the qemu command-line something like:
-netdev vknet,id=vke0 -device virtio-net,netdev=vke0
which would add a virtio network device for the guest, which is connected to the outside via the default vknetd socket ( /var/run/vknet ). The vknetd socket can also be explicitly specified, e.g. with:
-netdev vknet,id=vke0,sock=/var/run/myvknet -device virtio-net,netdev=vke0
> emulators/qemu-devel: Add vknet network backend for DragonFly's vknetd(1)

- ports/net/hping/dragonfly/patch-sendip.c
To ping ports on google.lt old behaviour is needed for dragonfly.
> net/hping: regen patch after free decided to use htons()

- ports/mail/antivirus-milter/Makefile.DragonFly
Untested: requires complicated setup
> mail/antivirus-milter: add alias

- ports/deskutils/plan/Makefile.DragonFly
- ports/deskutils/xmdiary/Makefile.DragonFly
- ports/devel/xxgdb/Makefile.DragonFly
- ports/japanese/skkfep/Makefile.DragonFly
- ports/x11/xautolock/Makefile.DragonFly
- ports/x11/xdtm/Makefile.DragonFly
For upcoming wait.h cleanup (removal of deprecated 4.4bsd union wait). 
Most of these can be patched in fports files/ patches directly.
Doesn't create compilation problems on 4.4, but might need version checking.
Affected ports so far:
deskutils/xmdiary
devel/xxgdb
deskutils/plan
japanese/plan
japanese/skkfep
x11/xautolock
x11/xdtm
> union wait removal

- ports/devel/tbb/Makefile.DragonFly
Nasty case of __STDC_LIMIT_MACROS in stdint.h and c++.
Will revisit it in next version, cause linux handles it differently.
At least archivers/par2cmdline-tbb works with new version
and pass all the tests. So shouldn't have impact on them.
> devel/tbb: for now use c++11 explictly

- ports/databases/tokyotyrant/dragonfly/patch-myconf.h
Tests:
ttserver & ; gmake check [ALL OK]
databases/p5-tokyotyrant:
ttserver & ; make test
PERL_DL_NONLAZY=1 /usr/local/bin/perl5.20.3 "-Iblib/lib" "-Iblib/arch" test.pl
ok 1 - tcrtest.pl write -tout 3 127.0.0.1 10000
ok 2 - tcrtest.pl read -tout 3 127.0.0.1
ok 3 - tcrtest.pl remove -tout 3 127.0.0.1
ok 4 - tcrtest.pl rcat -tout 3 127.0.0.1 1000
ok 5 - tcrtest.pl rcat -tout 3 -shl 10 127.0.0.1 1000
ok 6 - tcrtest.pl rcat -tout 3 -dai 127.0.0.1 1000
ok 7 - tcrtest.pl rcat -tout 3 -ext put 127.0.0.1 1000
ok 8 - tcrtest.pl misc -tout 3 127.0.0.1 1000
1..8
> databases/tokyotyrant: add dragonfly

- ports/security/openca-tools-forked/dragonfly/patch-configure
Have no tests and p5-openxpki requires quite a setup to test.
> security/openca-tools-forked: add dragonfly

- ports/games/redeclipse/dragonfly/patch-src_engine_shader.cpp
clang36 compilation is fine with both, g++50 is not.
taken-from upstream(quick temp fix until next version)
game needs manual -data compilation by user
> games/redeclipse: forgot to git add runtime patch

- ports/x11/i3status/Makefile.DragonFly
- ports/x11/i3status/dragonfly/hellno-pulseaudio.diff
Looks like bapt forgot to include DragonFly in extra patch while
handling upstream forced req on libpulse (not default OPTION).
So this takes care of PULSEAUDIO option handling on dports side.
Tested (ofc just w/ "default" options mode)
Both battery stats and cpu tz temps are still reported correctly.
> x11/i3status: unbreak build on new version

- ports/audio/cd-discid/dragonfly/patch-cd-discid.c
- ports/audio/py-cddb/dragonfly/patch-unix_cdrommodule.c
Not sure if these are correct, don't have any audio-cds
so adding not as alias but as patches to grep.
There are quite many audio ports with lots of runtime deps,
so this will help a bit even if these aren't fully functional.
> audio/cddb: add dragonfly

- special/Mk/diffs/bsd.commands.mk.diff
This fixes shebangs at least in devel/libcheck:bin/checkmk
AWK?=awk comes from share/mk/sys.mk
> Mk/bsd.commands.mk: redef AWK in case of short form

- ports/audio/beep/Makefile.DragonFly
No dev/speaker/speaker.h header and /dev/speaker device.
> audio/beep: mark as ignored

- ports/audio/volumeicon/Makefile.DragonFly
> audio/volumeicon: fix configure

- ports/audio/clunk/dragonfly/patch-clunk_hrtf.cpp
- ports/audio/clunk/dragonfly/patch-clunk_source.cpp
Depends on subst of OPTIONS_DEFAULT_x86_64=SSE (from _amd64)
> audio/clunk: fix build

- ports/x11-drivers/xf86-input-evdev/Makefile.DragonFly
ivadasz says that it still useful if someone would want to
write/port device driver that uses evdev device file and it
would useful if userspace tools would be already available.
> x11-drivers/xf86-input-evdev: drop webcamd run dep

- ports/x11-drivers/xf86-input-wacom/Makefile.DragonFly
> x11-drivers/xf86-input-wacom: remove wbcamd run dep

- ports/www/w3m/Makefile.DragonFly
lots of work to implement linux fb compat would be needed, so just disable
X11 backend should still work.
Unbreaks:
www/w3m (w/ INLINE_IMAGE option)
www/w3m-img
japanese/w3m-img
> www/w3m: disable fb (frambuffer)

- ports/emulators/qemu-devel/Makefile.DragonFly
- ports/emulators/qemu-devel/dragonfly/vknet-patch
based on changes to net/vde.c
Have no idea about internals of bridges nor bsd_user
Seems to work:
qemu-system-x86_64 -cdrom /data/dfly-x86_64-4.4.1.iso
> emulators/qemu-devel: just an educated guess

- ports/sysutils/hal/Makefile.DragonFly
- ports/sysutils/hal/dragonfly/patch-hald_freebsd_probing_probe-volume.c
After leaf/~zrj/cd9660_changes, for now just on pending state
cause i need to acquire base version bump token.
Basically currently hal compilation relies on __FreeBSD_version
evaluating as 0, that is bad.
Btw synth always recompile devel/nspr and friends ..
> sysutils/hal: to prevent gnome fallout after isofs/cd9660 changes

- ports/devel/boost-libs/dragonfly/patch-boost_math_tools_config.hpp
reasoning: was not packed before (check-plist orphans)
also quastionable if x87 register spill up into memory
is even predictable and trow safe in cxx
> devel/boost-libs: disable long double libs

- ports/devel/android-tools-simpleperf/Makefile.DragonFly
Seems there is some regex_error in cxx
Look into MF, free10 also had this problem.
For us just UNIMPLEMENTED.
> devel/android: fix synth test (disable test)

- ports/sysutils/ah-tty/Makefile.DragonFly
Disabled static bin building for now,
devel/ncurses has a separated -ltinfo from ncurses
and since configure doesn't detect that better to avoid that.
> sysutils/ah-tty: fix ncurses

- ports/lang/pcc/dragonfly/patch-os_dragonfly_ccconfig.h
gcc41 is not available, use gcc50
Tested: pcc -g test/1.c works even in gdb (-g)
> lang/pcc: Fix system compiler paths

- ports/cad/kicad-devel/Makefile.DragonFly
Technically it is a boost bug and kicad should actually test
boost headers for caps (deal with BOOST_MATH_DISABLE_FLOAT128).
For now just explicitly activate the literals extension.
Breakage reason: kicad no longer uses "safe" internal boost contrib.
> cad/kicad-devel: Build fix

- ports/sysutils/devfw-amdgpu/newport/Makefile
- ports/sysutils/devfw-bwn/newport/Makefile
- ports/sysutils/devfw-i915/newport/Makefile
- ports/sysutils/devfw-radeon/newport/Makefile
For some reason I thought it is enough to just set NO_ARCH
Should avoid the:
DEVELOPER_MODE: Notice: arch ... no architecture specific files found:
> sysutils/devfw-*: Set NO_ARCH to 'yes'

- ports/x11-drivers/xf86-video-ati/Makefile.DragonFly
- ports/x11-drivers/xf86-video-ati/STATUS
- ports/x11-drivers/xf86-video-ati/newport/Makefile
- ports/x11-drivers/xf86-video-ati/newport/distinfo
- ports/x11-drivers/xf86-video-ati/newport/files/patch-src__radeon_kms.c
- ports/x11-drivers/xf86-video-ati/newport/files/patch-src_radeon_accel.c
- ports/x11-drivers/xf86-video-ati/newport/pkg-descr
- ports/x11-drivers/xf86-video-ati/newport/pkg-plist
Current oficial 7.7 version performs better on xorg v1.17.4.
Also, contains both new supported hardware (like R7 360 bonaire)
and driver fixes that are hard to backport back to 7.5 version.
Tested-on: master w/ JUNIPER, CAICOS, OLAND and BONAIRE cards.
> x11-drivers/xf86-video-ati: Newport it to update.

- ports/sysutils/devfw-radeon/newport/Makefile
Simplifies the transition and more future safe.
> sysutils/devfw-radeon: Use more backwards compatible module naming.

- ports/sysutils/devfw-bwn/newport/Makefile
This port not should be distributed as binary package.
> sysutils/devfw-bwn: tune packaging

- ports/www/node/dragonfly/patch-deps_uv_src_unix_stream.c
- ports/www/node/dragonfly/patch-deps_uv_src_unix_tty.c
This is a [bug][1] in libuv. The type of a named pipe was not correctly
identified on DragonFly, which led to the following problems in node:
internal/process/stdio.js:152
throw new Error('Implement me. Unknown stream file type!');
^
Error: Implement me. Unknown stream file type!
at createWritableStdioStream (internal/process/stdio.js:152:13)
at process.stderr (internal/process/stdio.js:25:14)
at Socket._destroy (net.js:476:25)
at Socket.destroy (net.js:510:8)
at maybeDestroy (net.js:434:12)
at Pipe.onread (net.js:562:5)
[1]: https://github.com/libuv/libuv/pull/884
> Fix a longstanding issue with named pipes in libuv

- ports/multimedia/handbrake/Makefile.DragonFly
- ports/multimedia/handbrake/dragonfly/patch-contrib_ffmpeg_module.defs
- ports/multimedia/handbrake/dragonfly/patch-make_include_main.defs
Someone at users@ mentioned that it doesn't build.
Fix is quite trivial and still alows to have synth test pass
even with lots of contrib packages.
No runtime GUI test, cause of GTK3->dbus
> multimedia/handbrake: Build fix

- ports/graphics/embree/Makefile.DragonFly
- ports/graphics/embree/dragonfly/patch-common_sys_alloc.cpp
All of these were done for "speed" in a very unclean way,
restore to simpler form.
> graphics/embree: Restore previous variants

- ports/x11-servers/xwayland/newport/Makefile
- ports/x11-servers/xwayland/newport/pkg-descr
I was quite surprised that (at least for the xwayland from the 1.17.xx xserver), building Xwayland as a slave port like xephyr seems to just work out, without any special configure flags needed :)
The main issue left is that we should have all the options available in the master xorg-server port's Makefile (DEVD, HAL and SUID) disabled by default.
based on https://github.com/DragonFlyBSD/DPorts/issues/178
thanks to peeterm007 for looking at this again, and providing some motiviation to get this done.
> x11-servers/xwayland: Add newport similar to xephyr for Xwayland.

- ports/www/npm/Makefile.DragonFly
Since the acceptance of the patch to libuv introduced in https://github.com/DragonFlyBSD/DeltaPorts/pull/452 the module uidNumber works with nodejs. As a result, the patch introduced in https://github.com/DragonFlyBSD/DeltaPorts/pull/1 is no longer required.
> www/npm: Remove obsolete patch

- ports/benchmarks/stress-ng/dragonfly/patch-stress-shm.c
DragonFly doesn't provide implementation of posix_fallocate()
so fallback to ftruncate() like it is done in gold linker..
> benchmarks/stress-ng: attempt to fix build

- ports/www/firefox-lite/Makefile
- ports/www/firefox/Makefile.DragonFly
Intended to avoid dep on gtk3 and ensure gtk2 one still functional.
Build order:
first rebuild www/firefox to include updated MD
then in separate build, attempt the www/firefox-lite slave
> www/firefox: Add slave port for lite package

- ports/comms/kermit/Makefile.DragonFly
- ports/comms/kermit/dragonfly/patch-ckcdeb.h
- ports/comms/kermit/dragonfly/patch-ckucmd.c
kermit runs, ncurses functional.
Very complicated low level port, useful for headers testing.
> comms/kermit: Fix build.

- ports/emulators/bsvc/dragonfly/patch-Framework_Interface.cxx
- ports/emulators/bsvc/dragonfly/patch-sim68000_devices_M68681.cxx
- ports/emulators/bsvc/dragonfly/patch-sim68360_devices_M68681.cxx
Emulator starts in GUI tk/tcl mode, RAM registers all are there.
> emulators/bsvc: Fix c in not c stuff.

- ports/emulators/vpcs/Makefile.DragonFly
- ports/emulators/vpcs/dragonfly/patch-src_command.c
This is silly, once upon a time unixes refered to system compilers as 'cc'
TUI works, interactive.
> emulators/vpcs: Fix build.

- ports/emulators/stella/dragonfly/patch-configure
Requires external config files to start.
> emulators/stella: Add dragonfly to known systems.

- ports/emulators/skyeye/Makefile.DragonFly
Requires too much work to get working for little benefit.
> emulators/skyeye: Mark as ignored.

- ports/emulators/gem5/Makefile.DragonFly
Very heavy ARM emulator, builds in serial and very long.
Given that simple alias is enough and that it might be useful
for someone to do further develop.
But given that it will fail too often just adding IGNORE= slow build
> emulators/gem5: Use alias and mark ignored

- ports/net/dosdetector/Makefile.DragonFly
- ports/net/dosdetector/dragonfly/patch-include_dos.h
Program starts when ran by root, attaches to re0, but dunno how to test it.
> net/dosdetector: Fix build

- ports/devel/vtable-dumper/Makefile.DragonFly
Tried on /usr/lib/gcc50/libstdc++.so.9
works with mandled and demangled output.
> devel/vtable-dumper: Fix libelf detection.

- ports/ftp/llnlxftp/Makefile.DragonFly
X11 ftp program dated 1995 that has a tendency to segfault. Just ignore.
> ftp/llnlxftp: Mark as ignored.

- ports/x11-clocks/wmclockmon/Makefile.DragonFly
- ports/x11-clocks/wmclockmon/dragonfly/patch-configure
Small clock widget runs, can be configured
> x11-clocks/wmclockmon: Add support for DragonFly

- ports/sysutils/xmbmon/Makefile.DragonFly
Could be made working but too much effort while there are cleaner
alternatives, also due to heavy patching prune to probing wrong stuff.
> sysutils/xmbmon: Mark as ignored

- ports/devel/bam/dragonfly/patch-src_platform.h
Requires bam.lua as input so untested
> devel/bam: Add DragonFly to unix family

- ports/net/trafshow3/Makefile.DragonFly
uses things like "register", return (u_char *)0 and ncurses.
> net/trafshow3: Mark as ignored

- ports/misc/xiphos/Makefile.DragonFly
Didn't even bothered to build, reason DBUS,webkit-gtk3
muscles have those built so it would be faster
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65042
> misc/xiphos: Attempt to build

- ports/sysutils/u-boot-bananapi/Makefile.DragonFly
- ports/sysutils/u-boot-beaglebone/Makefile.DragonFly
- ports/sysutils/u-boot-cubieboard/Makefile.DragonFly
- ports/sysutils/u-boot-cubieboard2/Makefile.DragonFly
- ports/sysutils/u-boot-cubox-hummingboard/Makefile.DragonFly
- ports/sysutils/u-boot-duovero/Makefile.DragonFly
- ports/sysutils/u-boot-pandaboard/Makefile.DragonFly
- ports/sysutils/u-boot-rpi/Makefile.DragonFly
- ports/sysutils/u-boot-rpi2/Makefile.DragonFly
- ports/sysutils/u-boot-utilite/Makefile.DragonFly
- ports/sysutils/u-boot-wandboard/Makefile.DragonFly
There is little point to build U-boot loaders for little micros
from DragonFly.
> sysutils/u-boot-*: Ignore all

- ports/devel/simavr/Makefile.DragonFly
Lots of freebsd patches and twice of that dragonfly ones.
Given that it is for avr cpu emulation, skip for now.
> devel/simavr: Mark as ignored

- ports/sysutils/ua/dragonfly/patch-filei.cc
While it is considered bad practice to use either bzero or memset
in c++ in this case it is relatively safe.
This utility very usefull to easily gather dup files in handy output:
$ find /usr/src/ -type f | ua -
> sysutils/ua: Fix posix c in not c (bzero)

- ports/sysutils/wmdiskmon/Makefile.DragonFly
- ports/sysutils/wmupmon/Makefile.DragonFly
They could be made to compile and run, but doesn't give expected results.
> sysutils/wm{up,disk}mon: Mark as broken.

- ports/sysutils/jobd/Makefile.DragonFly
While it compiles, it lacks any support for DragonFly rc:
**WARNING** Unable to determine the correct rc script to install
Since it is untested, just skip.
> sysutils/jobd: Mark as ignored.

- ports/sysutils/nvramtool/Makefile.DragonFly
Utility works, just not very useful on DragonFly cause it is
intended for coreboot(opensource bios) boot.
Still utility is very simple and can dump the cmos contents.
> sysutils/nvramtool: Use alias

- ports/sysutils/geomgui/Makefile.DragonFly
This port intended for FreeBSD geom layer, that DragonFly doesn't use
> sysutils/geomgui: Mark as ignored

- ports/deskutils/cal/Makefile.DragonFly
USES+= alias is a no go, port doesn't honour the CFLAGS.
Calenddar utility runs and has good looking to it.
> deskutils/cal: Fix build

- ports/www/chromium/Makefile.DragonFly
- ports/www/chromium/diffs/Makefile.diff
- ports/www/chromium/dragonfly/patch-third_party_usrsctp_usrsctplib_usrsctplib_netinet_sctp_os.h
Lots of shifting around, but it builds for synth just-build
synth test fails because activates TEST option and build fails on linux testing sources
dunno what is missing for those
Just build fix, untested runtime! archived version at ~zrj/dports/chromium_try.tar.bz2
btw i just pushed some stuff directly, and it didn't got into last run (rsync?)
> www/chromium: Attempt to allow build new version

- ports/security/py-fail2ban/dragonfly/patch-config_action.d_pf.conf
> security/py-fail2ban: Fix pfctl path on DragonFly

- ports/devel/clanlib1/dragonfly/patch-Sources_Core_System_Unix_init_linux.cpp
- ports/games/orbital_eunuchs_sniper/dragonfly/patch-src_snipe2d.cpp
- ports/games/zatacka/dragonfly/patch-src_main.cpp
- ports/sysutils/cdargs/dragonfly/patch-src_cdargs.cc
Changes after <pthread.h> cleanup in
http://gitweb.dragonflybsd.org/dragonfly.git/commit/32cb82727ec681e604bb5631909bd642cd14fe5a
<limits.h> no longer get implicitly added into ns.
Cleaner C++ headers == faster compile time.
No functional change, only should affected cxx bits that rely on n/p
> cxx: Explicitly add limits.h for PATH_MAX visibility.

- ports/x11-drivers/xf86-input-joystick/Makefile.DragonFly
> x11-drivers/xf86-input-joystick: convert to USE+= autoreconf

- ports/archivers/zoo/Makefile.DragonFly
ptrerror.c actually has a dep on <stdarg.h> cause of STDARG
so just patch dep in makefile.
While there, throw in the alias to OpenBSD for timestamps handling.
Archiver works as intended
> archivers/zoo: Fix makefile deps.

- ports/cad/openscad/Makefile.DragonFly
Technically this is not a bug in openscad.
It got broken after updated math/cgal that causes problems in handling
the #if !defined(BOOST_NO_CXX11_VARIADIC_TEMPLATES) yup da boost issues
For now just shoehorn the -std=gnu++11 and silence few warns,
to show up real issues (cgal headers a quite noisy)
> cad/openscad: Fix build

- ports/devel/cargo/Makefile.DragonFly
- ports/devel/cargo/diffs/distinfo.diff
- ports/devel/cargo/dragonfly/patch-Cargo.lock
- ports/devel/cargo/dragonfly/patch-src_snapshots.txt
This uses a new cargo snapshot I built, plus some minor fixes
(crate version of fs2 0.2.3 -> 0.2.5).
> Fix cargo 0.11.0

- ports/devel/gdb/dragonfly/amd64dfly-nat.c
- ports/devel/gdb/dragonfly/dfly64.mh
It builds in synth and runs on simple quick small programs.
Just one thing: on "layout split && break main && run" sometimes gdb segfaults.
Seems like ncurses issue, but mostly it works.
DragonFly support in gdb should be really be fixed and upstreamed...
> devel/gdb: Fix build after new patches

- ports/devel/e2fsprogs-libss/diffs/Makefile.diff
- ports/sysutils/e2fsprogs/Makefile.DragonFly
- ports/sysutils/e2fsprogs/dragonfly/patch-lib_ext2fs_tdb.c
- ports/sysutils/e2fsprogs/dragonfly/patch-lib_ext2fs_unix__io.c
- ports/sysutils/e2fsprogs/dragonfly/patch-lib_support_plausible.c
For now just disable m_hugefile test, no idea why it would fail
also expand patching
Update: disable d_dumpe2fs_group_only, fails on synth test...
also leaves /etc/blkid.tab behind in base..
> sysutils/e2fsprogs: Fix build after enabled tests

- ports/audio/ccaudio2/Makefile.DragonFly
- ports/devel/commoncpp/Makefile.DragonFly
- ports/devel/commoncpp/dragonfly/patch-config.h.in
- ports/devel/commoncpp/dragonfly/patch-src_serial.cpp
- ports/devel/commoncpp/dragonfly/patch-src_socket.cpp
- ports/devel/commoncpp/dragonfly/patch-src_thread.cpp
- ports/devel/commoncpp/dragonfly/patch-src_timer.cpp
commoncpp installs common headers that are used by ports depending on it.
Since it building CFLAGS aren't fully considered everywhere it is better
to patch such ports directly to provide fixed headers than depend on
implicit alias + strange patches in other ports.
This fixes another case of upcoming POSIX ns cleanup in base.
Specifically net/panoptis that for now passes w/o any patching.
To rebuild: audio/ccaudio2 devel/commoncpp net/panoptis
Disected-by: swildner
> devel/commoncpp: Convert alias to patches

- ports/www/chromium/dragonfly/patch-third__party_ffmpeg_ffmpeg.gyp
For upcoming header cleanup, similar patch is available
as freebsd conditional files/extra-patch-gcc but:
1) doesn't apply to our gcc5 very well
2) likely will be gone together w/ f9
3) just removing the defines is simplier to track
Submitted-by: swildner (tested on poudriere 6.4h build at -j1)
> www/chromium: Fix ffmpeg contrib strict POSIX env

- ports/www/firefox/Makefile.DragonFly
Provisionally for now to allow users to test webrtc speaker/mic communications.
Something strange with rust, it has internal compiler error maybe master ABI change.
w/o rust option it compiles fine in synth.
> www/firefox: Enable webrtc and pulseaudio in it.

- ports/x11-toolkits/gtk30/Makefile.DragonFly
- ports/x11-toolkits/gtk30/dragonfly/patch-atk-bridge-option
Controversal issue:
https://bugzilla.gnome.org/show_bug.cgi?id=677491
Also even at freebsd-ports:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=194460
Since we try to keep ports lean&fast and prefer to respect users choices
just add Jan Beich pending fix. (very unlikely to break in the future)
To keep upstream happy default behaviour is not changed.
If user compiles his set with OPTIONS_UNSET=DBUS this needs to be respected
and any artificial blockers should be patched out to ensure users freedom
to run their system as they see fit (even if that means patching).
As for me this allows to finally runtime test gtk3 ports too.
At least textproc/meld works fine and looks like I no longer need to use
ancient meld with gtk2 and hope updated deps stay compatible.
> x11-toolkits/gtk30: Mark missing dbus dependencies

- ports/databases/cppdb/Makefile.DragonFly
Author: riggs <riggs@FreeBSD.org>
Date:   Sun Jul 17 06:46:45 2016 +0000
Build with ninja to reduce build time
PR:             210725
Submitted by:   info@babaei.net (maintainer)
Ok, lets check if it needs speeding up, w/o ninja first:
synth test databases/cpp
24.123u 7.958s 0:27.40 117.0%   5671+773k 17630+94io 102pf+0w
Are you fricking kidding me?!?
> databases/cppdb: Revert 'use ninja'

- ports/net-im/telegram-purple/Makefile.DragonFly
- ports/net-im/telegram-purple/dragonfly/patch-tgl_mtproto-client.c
Help to find -lgcypt and disable -Werror=return-type for dummy funcs.
> net-im/telegram-purple: Fix build on new version

- ports/ftp/R-cran-curl/dragonfly/patch-src_nslookup.c
In ports FreeBSD had a general patch, yet upstreamed just their case.
Patch accordingly for DragonFly too.
Btw, shouldn't main math/R port be somewhat more like: http://sprunge.us/XWOT
> ftp/R-cran-curl: Fix build on new version.

- ports/biology/seqtools/dragonfly/patch-gbtools_src_include_blatSrc_fof.c
On DragonFly FILE is __FILE typedef, so avoid:
error: arithmetic on pointer to an incomplete type
by casting it to public complete type.
> biology/seqtools: Fix FILE issue.

- ports/net/xorp/Makefile.DragonFly
- ports/net/xorp/dragonfly/patch-libcomm_comm__sock.c
- ports/net/xorp/dragonfly/patch-rtrmgr_lex.boot.cc
- ports/net/xorp/dragonfly/patch-rtrmgr_lex.opcmd.cc
- ports/net/xorp/dragonfly/patch-rtrmgr_lex.tplt.cc
Note to myself: don't be lazy, use patches and drop alias.
We can't use alias cause it causes problems in lipcap defines in headers.
Should we alias to freebsd in libpcap headers? nfc.
> net/xorp: Fix build after updated libpcap in dports.

- ports/net/libpcap/dragonfly/patch-gencode.c
How this could have passed through all quality checks?
Allows to build my package set w/o IPV6 option set.
> net/libpcap: Fix build w/o IPV6

- ports/net/tcpview/dragonfly/patch-ostype
Mainly to allow to build in synth.
Should apply to other arches as well.
> net/tcpview: Add fallback if /etc/motd is missing.

- ports/sysutils/bareos-server/Makefile.DragonFly
client-static nees ncurses and gettext(-lintl).
Rebuild master port sysuitls/bareos-server first.
> sysutils/bareos-client-static: Fix last failing port of bareos.

- ports/math/clblas/Makefile.DragonFly
- ports/math/clblas/dragonfly/patch-src_CMakeLists.txt
- ports/math/clblas/dragonfly/patch-src_library_CMakeLists.txt
- ports/math/clblas/dragonfly/patch-src_samples_CMakeLists.pack
Even if I don't approve boost usage in OpenCL stuff, well, it makes a good testcase,
so fix cripplings of gcc (other compilers would not handle it anyway).
CLOCK_REALTIME on dlfy is visible later in POSIX.
This installs extra file in case of gcc, so PLIST_FILES+= trick is ok?
or should i just patch so that pc file is not install even for gcc case?
> math/clblas: Fix build.

- ports/devel/objecthash/dragonfly/patch-Makefile
- ports/devel/objecthash/dragonfly/patch-objecthash.h
GCC is right, static const int is not a "parameter" in C.
If clang accepts it then well it doesn't have a notion of file scopes..
Also disable -Werror=unused-but-set-variable
> devel/objecthash: Cure c++'ism.

- ports/net/cjdns/Makefile.DragonFly
- ports/net/cjdns/dragonfly/patch-crypto_random_seed_BsdKernArndSysctlRandomSeed.h
- ports/net/cjdns/dragonfly/patch-interface_tuntap_TUNInterface__freebsd.c
- ports/net/cjdns/dragonfly/patch-node__build_dependencies_libuv_src_unix_freebsd.c
- ports/net/cjdns/dragonfly/patch-node__build_make.js
- ports/net/cjdns/dragonfly/patch-util_platform_netdev_NetPlatform__freebsd.c
Well we might need KERN_ARNG syscall...
And libuv fix for correct full path on exec, not a relative in other ports too.
This one now has correct full path (/usr/.../exec).
There might be other issues but for now will do.
> net/cjdns: Fix build problems.

- ports/net/ndpi/Makefile.DragonFly
- ports/net/ndpi/dragonfly/patch-src_include_ndpi__define.h
- ports/net/ndpi/dragonfly/patch-src_include_ndpi__includes.h
- ports/net/ndpi/dragonfly/patch-src_include_ndpi__unix.h
- ports/net/ntopng/dragonfly/patch-include_DivertInterface.h
- ports/net/ntopng/dragonfly/patch-include_ntop__includes.h
- ports/net/ntopng/dragonfly/patch-src_DivertInterface.cpp
- ports/net/ntopng/dragonfly/patch-src_PacketDumperTuntap.cpp
- ports/net/ntopng/dragonfly/patch-src_main.cpp
- ports/net/ntopng/dragonfly/patch-third-party_mongoose_mongoose.c
Drop alias in net/ndpi (installs public headers w/ \__FreeBSD__) rebuild needed.
Add DragonFly for ntopng, but alias one place to OpenBSD.
> net/ntopng: Fix build

- ports/sysutils/ganglia-monitor-core/dragonfly/patch-libmetrics_dragonfly_metrics.c
While there fix one sysctlbyname(), others look suspicious too.
> sysutils/ganglia-monitor-core: Add missing dummies on new version.

- ports/databases/cego/dragonfly/patch-samples_cgplustest_CegoCPlusTest.cc
- ports/databases/cego/dragonfly/patch-src_CegoAdmin.cc
- ports/databases/cego/dragonfly/patch-src_CegoBufferPool.cc
- ports/databases/cego/dragonfly/patch-src_CegoClient.cc
- ports/databases/cego/dragonfly/patch-src_CegoMain.cc
- ports/databases/cego/dragonfly/patch-src_CegoNet.cc
- ports/databases/cego/dragonfly/patch-src_CegoRecoveryManager.cc
In new version getenv() was sprayed everywhere so we need <cstdlib>
> databases/cego: Fix new c in not c.

- ports/databases/libodbc++/dragonfly/patch-src_datastream.h
- ports/devel/antlr/dragonfly/patch-lib_cpp_antlr_CharScanner.hpp
- ports/devel/ddd/Makefile.DragonFly
- ports/devel/glrparser/dragonfly/patch-glr_glrGrammar.h
- ports/devel/libbinio/dragonfly/patch-src_binwrap.cpp
- ports/devel/xparam/dragonfly/patch-lib_antlr_antlr_CharScanner.hpp
- ports/devel/xparam/dragonfly/patch-lib_sources_xp__loader.cpp
- ports/games/rtb/dragonfly/patch-team-framework_io_unixoutstreambuf.cpp
- ports/games/shootingstar/dragonfly/patch-src_engine_dbg.cpp
- ports/graphics/panomatic/dragonfly/patch-panomatic_tclap_MultiArg.h
- ports/graphics/panomatic/dragonfly/patch-panomatic_tclap_ValueArg.h
- ports/textproc/scim-bridge/dragonfly/patch-agent_scim-bridge-agent-application.cpp
- ports/www/bookmarkbridge/dragonfly/patch-bookmarkbridge_main.cpp
- ports/www/swish++/dragonfly/patch-fdbuf.c
I would say .eof() should be used but hey,
also fix few cases where -1 should have been used (getopt())
> <cstdio> EOF in c++

- ports/audio/cmus/Makefile.DragonFly
- ports/audio/cmus/dragonfly/patch-configure
Now cmus configure uses pkg-config --cflags ncurses
and sets -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=600 directly to CFLAGS
in turn hiding the visibility of strndup().
Fix by just ignoring ncurses cflags.
> audio/cmus: Fix build on version.

- ports/lang/cilkplus/dragonfly/patch-runtime_os-unix.c
- ports/lang/cilkplus/dragonfly/patch-runtime_sysdep-unix.c
Just as I have in my gcc checkout. It builds passes most except
for CK runtime tests, problem in ld-elf.so (have a partial patch)
With rtld patch main body of cilk test works just still fails miserably in ld-elf.so when program is exiting (likely misses some destructor or calls them in wrong order or smth from c++ crap)
standalone testcase with gdb outputs: https://leaf.dragonflybsd.org/~zrj/cilk_fun/
> lang/cilkplus: Build fix.

- ports/editors/emacs/Makefile.DragonFly
- ports/editors/emacs/dragonfly/extra-gls_lisp_dired.el
- ports/editors/emacs/dragonfly/extra-ls_lisp_dired.el
Prevent calloc() optimization (just as for csh in base).
Also fix reports by emacs users that file viewer fails on special filenames.
Turns out emacs is very relying on ls having --dired flag support (gnu ls).
So if it fails it fallbacks to regexes on ls -l output that results in some
unselectable file entries.
Fix it by adding new option that uses gls from coreutils cause even swildner
doesn't like idea of adding --dired support in base ls. From gls(1):
-D, --dired
generate output designed for Emacs' dired mode
In case of GNULS=off, base ls is used, it works for standard filenames
(no whitespaces, special symbols or complicated symblinks --> ../../bin/../file)
so just enforce LC_TIME=C for ls -l invoke to ease up output for dodgy regexes.
> editors/emacs: Fix build w/ gcc50 and C-x C-f browser.

- ports/sysutils/intel-pcm/dragonfly/patch-Makefile
- ports/sysutils/intel-pcm/dragonfly/patch-client_bw.cpp
- ports/sysutils/intel-pcm/dragonfly/patch-client_bw.h
- ports/sysutils/intel-pcm/dragonfly/patch-cpucounters.cpp
- ports/sysutils/intel-pcm/dragonfly/patch-msr.cpp
- ports/sysutils/intel-pcm/dragonfly/patch-pci.cpp
- ports/sysutils/intel-pcm/dragonfly/patch-pci.h
* Works on master starting from a77600744cbcd5fad82397ef508492f6c2773ee3,
and DragonFly_RELEASE_4_6 after 34476392dab2544324d112e6127a8b1ef1c4c258.
* On older master or 4.6 kernels it causes a kernel panic when running.
> sysutils/intel-pcm: Port to DragonFly.

- ports/print/cups-filters/Makefile.DragonFly
- ports/print/hplip/Makefile.DragonFly
This port is very dirty, absolute symlinks, plist problems etc:
===> Staging rc.d startup script(s)
====> Running Q/A tests (stage-qa)
Warning: Bad symlink '/usr/local/bin/foomatic-rip' pointing to an absolute pathname '/usr/local/libexec/cups/filter/foomatic-rip'
--------------------------------------------------------------------------------
--  Phase: check-plist
--------------------------------------------------------------------------------
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: /etc/init.d/cups-browsed
Error: Orphaned: /etc/rc0.d/K00cups-browsed
Error: Orphaned: /etc/rc2.d/K00cups-browsed
Error: Orphaned: /etc/rc2.d/S99cups-browsed
Error: Orphaned: /etc/rc3.d/K00cups-browsed …
> print/cups-filters: Mark the mess.

- ports/devel/grantlee5/Makefile.DragonFly
- ports/devel/love07/Makefile.DragonFly
- ports/devel/love08/Makefile.DragonFly
- ports/devel/qca/Makefile.DragonFly
- ports/games/maxr/Makefile.DragonFly
- ports/games/pipewalker/Makefile.DragonFly
- ports/mail/trojita/Makefile.DragonFly
- ports/security/gpgme/Makefile.DragonFly
- ports/x11-toolkits/hs-wxc/Makefile.DragonFly
These ports looks like missinng -pthread flags, they do not use -pthread
by themselves but they link against libs that do (mostly libSDL and qt5).
ld.bfd is behaves differently so for now use it for linking.
Makes a good testcase for further base changes testing.
Should -pthread be used in these by default?
> libgcc_pic.a pack on missing -pthread

- ports/comms/fldigi/Makefile.DragonFly
New audio/libsamplerate has const float in SRC_DATA stuct, yet here
it is used with non-c++ memset(that is C).
Also try: games/voxelands and mail/qmail-conf
> comms/fldigi: Add -fermissive.

- ports/lang/perl5-devel/Makefile.DragonFly
- ports/lang/perl5.24/Makefile.DragonFly
In last PR forgot to git add perl5.24.
While there throw same patch for -devel version too.
> lang/perl5-2.24: Add patch like in perl.5.20

- ports/devel/binutils/dragonfly/patch-bfd_config.bfd
Base binutils are already patched by ivadasz.
No-op since --enable-targets=all but should be in binutils upstream so
that --enable-targets="x86_64-pc-dragonfly" would work out-of-the box.
> devel/binutils: add target for MS pei support.

- ports/math/vtk6/Makefile.DragonFly
MD removes a single file from it, given that vtk6 takes a long time
to compile, it will fail on synth test badly in the very end.
> math/vtk6: Fix empty directory in stage.

- ports/devel/libclc/Makefile.DragonFly
OpenCL on r7 360 now started to give:
Unknown attribute kind (8).
LLVM bytecode generated by llvm37 work fine in OpenCL.
> devel/libclc: Use same version as mesa ports(clover)

- ports/x11-toolkits/blt/Makefile.DragonFly
Linking against libtcl has circural deps and causes bunch of trig functions get
missing references. Avoid by explictly adding direct dep on -lm for main lib.
> x11-toolkits/blt: Add extra -lm.

- ports/math/clfft/Makefile.DragonFly
- ports/math/clfft/dragonfly/patch-src_library_CMakeLists.txt
- ports/math/clfft/dragonfly/patch-src_statTimer_statisticalTimer.CPU.h
clFFT.pc is only installed when gnu compiler is used.
Also throw in fresh FreeBSD change, it is unclear whats happening there.
> matc/clfft: Fix plist

- ports/devel/boost-libs/dragonfly/patch-boost_system_config.hpp
This fixes atleast www/anyterm (BUILD_DEPENDS) by avoiding linkage to
-lboost_system
> devel/boost-libs: Reduce compat deprecated stuff.

- ports/games/openbor/Makefile.DragonFly
- ports/games/openbor/dragonfly/patch-source_webmlib_halloc_align.h
FreeBSD removed the patch for max_align_t, since we don't want to add
such non standard additions to our standard libs just patch it directly.
While there use correct order for linking libs.
> games/openbor: Fix build after ports update.

- ports/devel/boost-libs/dragonfly/patch-boost_math_tools_config.hpp
Only packages that require this should do it explicitly.
Will help a lot while FreeBSD devs are messing up with clang 3.9.0 until
they come to certain conclusions about certain things.
Unbreaks devel/synfig after boot-libs update.
> devel/boost-libs: Disable implicit support for FLOAT128.

- ports/devel/boost-libs/dragonfly/patch-boost_container_detail_pair.hpp
Fixes at least net-p2p/twister
> devel/boost-libs: backport patch from upstream.

- ports/net-p2p/twister/Makefile.DragonFly
There will be more cases like this.. oopsie
> net-p2p/twister: Mark as using deprecated boost system api.

- ports/math/pdal/dragonfly/patch-newer_geotiff_support
Wow "lets check foreign lib include header guards"..
Should be broken on Freebsd too.
> math/pdal: Fix build against newer libgeotiff.

- ports/net-mgmt/bgpq3/dragonfly/patch-bgpq_expander.c
- ports/net-mgmt/bgpq3/dragonfly/patch-sx_slentry.h
Just use bundled sys/tree.h implementation.
Throw in sys/select.h for good measure too.
> net-mgmt/bgpq3: Unbreak build.

- ports/editors/calligra/dragonfly/patch-libs_db_drivers_sqlite_icu_CMakeLists.txt
-std=c90 does not accept c++ style comments ("//"), use -std=c99
> editors/calligra: Fix build after icu update.

- ports/net/samba43/Makefile.DragonFly
- ports/net/zebra-server/Makefile.DragonFly
- ports/science/InsightToolkit/dragonfly/patch-Modules_ThirdParty_NrrdIO_src_NrrdIO_CMakeLists.txt
- ports/textproc/lttoolbox/Makefile.DragonFly
mainly xml stuff and git add forgotten net/samba43 too
force-rebuilt (non bumped deps on shared libs)
textproc/lttoolbox
from previous pack:
astro/cfitsio
audio/id3lib
x11/gnustep-app
devel/dcmtk
devel/gorm
devel/hs-QuickCheck
devel/hs-text
graphics/freeimage
graphics/gexiv2
graphics/libsvg-cairo
graphics/libsvg
graphics/togl
mail/gnumail
security/hs-crypto-random
security/cryptonite
textproc/tinyxml
x11-toolkits/libgnomeprintui
x11/libXcm
> fix issues found by binutils 2.27 ld.gold pt2

- ports/astro/gpsd/Makefile.DragonFly
I'm a bit lost here, maybe because of no dbus build.
Synth test passes
> astro/gpsd: Work around scons logic for binutils 2.27.

- ports/databases/gtksql/Makefile.DragonFly
x11-toolkits/scintilla was updated to 371 and now needs deprecated defines.
Should be broken on freebsd-ports too (thus just adding compat define)
> databases/gtksql: Fix build after freebsd-ports update.

- ports/sysutils/freefilesync/Makefile.DragonFly
Heavy patches, keep anyway, uses c++14, so makes a good testcase.
Very heavy GUI utility, it seem to run, but didn't tried sync bit.
> sysutils/freefilesync: Fix build issues.

- ports/devel/boost-all/diffs/compiled.mk.diff
- ports/devel/boost-libs/diffs/pkg-plist.diff
Maybe it would be better if was done on freebsd-ports side, dunno but:
Must use at least -std=c++11 while compiling the libs (partially wrong abi)
boost headers has no safe-guards when compiled w/ -std=c++98, while most of
packages rely on -std=c++11 while using these boost headers.
Explains why certain things doesn't seem right here and there.
@@ -291,19 +301,19 @@ Performing configuration checks
- sparc                    : no
- x86                      : yes
- symlinks supported       : yes
-    - C++11 mutex              : no
+    - C++11 mutex              : yes
- lockfree boost::atomic_flag : yes
-    - Boost.Config Feature Check: cxx11_auto_declarations : no
-    - Boost.Config Feature Check: cxx11_constexpr : no
-    - Boost.Config Feature Check: cxx11_defaulted_functions : no
+ …
> devel/boost-libs: uncriple the boost-libs

- ports/net/freerdp/dragonfly/patch-winpr_tools_makecert_CMakeLists.txt
Might need to be converted to extra patch because of release-4.6
> net/freerdp: Fix dports libcrypto.so detection.

- ports/graphics/aqsis/Makefile.DragonFly
Use c++11 (there is no outrunning this one), and small code bug.
There are two more patches from arch to investigate but maybe later.
> graphics/aqsis: Fix for updated boost-libs.

- ports/sysutils/metricbeat/Makefile.DragonFly
Fails on Mtimespec vs Mtim in docker, not sure of any of these.
build fix only.
> sysutils/metricbeat: Unbreak build

- ports/graphics/sdl2_gfx/Makefile.DragonFly
Force-rebuild: graphics/sdl2_gfx (for games/manaplus)
> graphics/sdl2_gfx: Add missing link against -lm (ld.gold)

- ports/comms/sdr-wspr/Makefile.DragonFly
Even Darwin case just hardcodes full path..
> comms/sdr-wspr: Fix -lportaudio search.

- ports/math/wxMaxima/Makefile.DragonFly
silent failure on configure while linking with wxWidgets.
> math/wxMaxima: Must use -std=c++11.

- ports/audio/shairport-sync/Makefile.DragonFly
- ports/audio/shairport-sync/dragonfly/patch-common.h
It is likely better to move it to MF, but with avahi plain
-L${LOCALBASE}/lib in LDFLAGS might not be good on freebsd
> audio/shairport-sync: Workaround LDFLAGS issue.

- ports/devel/hs-hslua/dragonfly/patch-hslua.cabal
- ports/graphics/hs-JuicyPixels/dragonfly/patch-JuicyPixels.cabal
- ports/graphics/hs-dia-functions/dragonfly/patch-dia-functions.cabal
- ports/math/hs-mwc-random/dragonfly/patch-mwc-random.cabal
Explicitly link with libm to allow building rest of Haskell ports.
Before incremental remove these 4 binary txz:
hs-hslua-*.txz hs-JuicyPixels-*.txz hs-dia-functions-*.txz hs-mwc-random-*.txz
> binutils 2.27 ld.gold workarounds pt2

- ports/devel/subversion/diffs/Makefile.diff
User request: the way template is contructed causes issues with python tools.
I didn't asked for more details, but given that files/extra-patch-fbsd-template
performs direct subversion code modification it is better to ship original.
> devel/subversion: Do not provide freebsd template by default.

- ports/devel/libuv/dragonfly/patch-src_unix_freebsd.c
Using procfs is considered deprecated, noticed while tinkering with
lang/julia bundled libuv.
> devel/libuv: Prefer to use sysctl to get path.

- ports/mail/rspamd/dragonfly/patch-src_libutil_http.c
Rspamd tried to call shm_open(3) with a path in the root filesystem
(e.g. /rhm.3f0fd440d46fac91e1b4). Obviously, this fails due to wrong
permissions, and in effect this makes rspamd very slow and probably it
cannot perform it's job (spam filtering) at all.
Lots of lines like the following were found in
/var/log/rspamd/rspamd.log before this patch:
rspamd_shmem_mkstemp: /usr/obj/dports/mail/rspamd/rspamd-1.4.1/src
/libutil/util.c:1970: failed to create temp shmem
/rhm.3f0fd440d46fac91e1b4: Permission denied
This patch fixes the problem by creating the shm files in /tmp. With
this patch applied, these lines are gone from the log.
> Fix shm permission problem of rspamd on DragonFly

- ports/devel/lxqt-build-tools/dragonfly/patch-cmake_modules_LXQtCreatePkgConfigFile.cmake
Location override of .pc install dir were moved to another port.
Now they are in devel/lxqt-build-tools, so just move the patch.
> devel/liblxqt: Move patch to another port.

- ports/security/py-xmlsec/dragonfly/patch-x509.c
It is unclear why prototype mismatch started to happen.
> security/py-xmlsec: Fix build.

- ports/math/coq/dragonfly/patch-configure.ml
Should be enough there are too many things to rebuild cleanly in synth for me to get to ocaml package.
> math/coq: Use md5 on DragonFly

- ports/lang/cling/dragonfly/patch-cmake_modules_HandleLLVMOptions.cmake
Fails just on environ symbol during .so link.
> lang/cling: Add missing patch.

- ports/graphics/jogamp-jogl/Makefile.DragonFly
- ports/graphics/jogamp-jogl/dragonfly/patch-gluegen_make_gluegen-cpptasks-base.xml
Activate freebsd-clang mode. Alternative is to write full-blown native
DragonFly handling but that will not be done by me.
> graphics/jogamp-jogl: push /usr/local/includes down.

- ports/games/fishsupper/Makefile.DragonFly
This port is not ready for -std=c++11 but given that free
removed their specific .if ${OPSYS} == FreeBSD to limit patching
just follow along, and force -std=c++11 while adding -fpermissive.
> games/fishsupper: Fix patching for broken libc++.

- ports/www/libhpack/dragonfly/patch-CMakeLists.txt
- ports/www/libhpack/dragonfly/patch-libchula_buffer.c
- ports/www/libhpack/dragonfly/patch-libchula_buffer.h
- ports/www/libhpack/dragonfly/patch-libchula_test_buffer__test.c
- ports/www/libhpack/dragonfly/patch-libchula_test_util__test.c
- ports/www/libhpack/dragonfly/patch-libchula_util.c
- ports/www/libhpack/dragonfly/patch-libchula_util.h
Programs should be tracking this, not rely on third party.
While there fix missing defs for htonls.
There are few tests failing on getgrnam().
> www/libhpack: Rip out malloc_size() and malloc_usable_size()

- ports/sysutils/ipmitool/dragonfly/patch-configure
As for compilation warnings, well it does use -Wpedantic
> sysutils/ipmitool: Use __BSD_VISIBILE on new version.

- ports/devel/unittest-cpp/dragonfly/patch-CMakeLists.txt
Just expand freebsd patch to include DragonFly too.
> devel/unittest-cpp: Fix .pc file install location.

- ports/x11-toolkits/fox17/dragonfly/patch-include_xincs.h
- ports/x11-toolkits/fox17/dragonfly/patch-lib_FXThread.cpp
Needed after base changes and port detecting presence of
pthread_setaffinity_np().
> x11-toolkits/fox17: Include <pthread_np.h>

- ports/lang/ruby23/diffs/pkg-plist.diff
Noticed while playing with deforaos build.
> lang/ruby23: Fix missing entry in plist.

- ports/lang/julia/dragonfly/patch-zzz_rpath
Julia plays with patchelf on soon to be installed execs and libraries.
Try to recover at least for base libstdc++.so.
Reported-by: profmakx@
> lang/julia: Somewhat fix rpath override.

- ports/science/v_sim/Makefile.DragonFly
some headers are not ISO C90 compatible (c++ comments)
> science/v_sim: Enforce -std=c99

- ports/net-mgmt/driftnet/Makefile.DragonFly
These functions are used in other sources and being marked as inline so gcc
does the right job by not emiting the symbol.
Strange how clang fails to inline them.
> net-mgmt/driftnet: Drop inline attribute for few functions.

- ports/x11-themes/adwaita-common/Makefile.DragonFly
Force rebuild all three (-qt4 and -qt5 uses main Makefile w/ USES=metaport):
x11-themes/adwaita-common
x11-themes/adwaita-qt4
x11-themes/adwaita-qt5
> x11-themes/adwaita-*: Fix isnan for non leaky compiler.

- ports/irc/irssi-xmpp/Makefile.DragonFly
There is something strange about why patch was added by freebsd.
> irc/irssi-xmpp: Use contra patch.

- ports/devel/llvm40/Makefile.DragonFly
- ports/devel/llvm40/dragonfly/clang-patch-add_flto_support
- ports/devel/llvm40/dragonfly/clang-patch-wrong_predefs
- ports/devel/llvm40/dragonfly/openmp-patch-tools_openmp_runtime_cmake_LibompMicroTests.cmake
- ports/devel/llvm40/dragonfly/openmp-patch-tools_openmp_runtime_src_kmp.h
- ports/devel/llvm40/dragonfly/openmp-patch-tools_openmp_runtime_src_kmp__ftn__entry.h
- ports/devel/llvm40/dragonfly/openmp-patch-tools_openmp_runtime_src_kmp__platform.h
- ports/devel/llvm40/dragonfly/openmp-patch-tools_openmp_runtime_src_kmp__runtime.cpp
- ports/devel/llvm40/dragonfly/openmp-patch-tools_openmp_runtime_src_kmp__wrapper__malloc.h
- ports/devel/llvm40/dragonfly/openmp-patch-tools_openmp_runtime_src_z__Linux__util.cpp
Same ones as llvm39 for OpenMP implementation as libomp.so.
While there remove few strange predefs for DragonFly.
Also throw in proper support for -flto handling in the toolchain,
mainly to pass LLVMgold.so to the linker to be used as plugin.
> devel/llvm40: Add usual patches.

- ports/lang/ghc/dragonfly/patch-rts_posix_OSThreads.c
Same as it is done for freebsd, will be needed for upcoming base changes
in headers namespaces.
While there add workaround for sysctl as last resort for dfly too.
> lang/ghc: Enable __BSD_VISIBLE on DragonFly.

- ports/net/opal/dragonfly/patch-plugins_video_common_platform.h
Will be needed for upcoming base headers namespace cleanup.
No functional change.
> net/opal: Make size_t visibility explicit.

- ports/emulators/qemu-devel/Makefile.DragonFly
- ports/emulators/qemu-devel/dragonfly/patch-configure
This brings back the qemu-system-x86_64 -m 4G -hda /zzz/qemu.img -curses
> emulators/qemu-devel: Re enable curses backend support.

- ports/security/doas/dragonfly/patch-env.c
Build log:
```
j1900# make
===>  License ISCL accepted by the user
===>   doas-5.9p7 depends on file: /usr/local/sbin/pkg - found
===> Fetching all distfiles required by doas-5.9p7 for building
===>  Extracting for doas-5.9p7
=> SHA256 Checksum OK for slicer69-doas-5.9p7-a15e6ed_GH0.tar.gz.
===>  Patching for doas-5.9p7
===>  Applying dragonfly patches for doas-5.9p7
===>   doas-5.9p7 depends on executable: gmake - found
===>  Configuring for doas-5.9p7
===>  Building for doas-5.9p7
gmake[1]: Entering directory '/usr/obj/dports/security/doas/doas-a15e6ed'
cc -pipe -O2 -fno-strict-aliasing -DUSE_PAM -DDOAS_CONF=\"/usr/local/etc/doas.conf\"   -c -o doas.o doas.c
cc -pipe -O2 -fno-strict-aliasing -DUSE_PAM -DDOAS_CONF=\"/usr/local/etc/doas.conf\"   -c -o env.o env.c
cc -pipe -O2 …
```
> security/doas: Fix build in DragonFly

- ports/x11-drivers/xf86-video-ati/STATUS
- ports/x11-drivers/xf86-video-ati/newport/Makefile
- ports/x11-drivers/xf86-video-ati/newport/Makefile.DragonFly
- ports/x11-drivers/xf86-video-ati/newport/distinfo
- ports/x11-drivers/xf86-video-ati/newport/files/patch-src__radeon_kms.c
- ports/x11-drivers/xf86-video-ati/newport/pkg-descr
- ports/x11-drivers/xf86-video-ati/newport/pkg-plist
There are several issues, one of them is the git patch I need to exclude
(reported by ftigeot that on his r600 card glamor causes issues) and
I do not want more surprises. So it is best to keep both ati and intel29
to be handled consistency. As for mesa update, so far i915 gpu hangs on
anything that involves OpenGL, in ftigeot case it was hard reset.
> x11-drivers/xf86-video-ati: Move back to be a newport.

- ports/ports-mgmt/poudriere-devel/newport/files/patch-src_etc_poudriere.conf.sample
swildner reported some strange differences between pou and direct from ports
compilation in logs like.
While comparing build logs i noticed that devel/m4 is compiled with
LIBSIGSEGV=on while dports not.
Turns out it is fetched by poudriere ports -c
> ports-mgmt/poudriere-devel: Change default DPorts.git location.

- ports/security/stunnel/dragonfly/patch-src_common.h
- ports/security/stunnel/dragonfly/patch-src_ctx.c
- ports/security/stunnel/dragonfly/patch-src_prototypes.h
- ports/security/stunnel/dragonfly/patch-src_ssl.c
- ports/security/stunnel/dragonfly/patch-src_sthreads.c
- ports/security/stunnel/dragonfly/patch-src_verify.c
* Current DPorts has security/stunnel v5.40, original patches applied,
but failed to build with LibreSSL v2.5.4;
* Upstream FreeBSD Ports has security/stunnel v5.41, original patches
failed to apply;
* Update the dfly-specific patches to match security/stunnel v5.41,
also fix the build issues with LibreSSL v2.5.4;
* Tested on DFly-4.9-DEVELOPMENT.
> security/stunnel: update patches for v5.41

- ports/lang/rust/dragonfly/patch-src_liblibc_src_unix_bsd_freebsdlike_dragonfly_mod.rs
This should prevent cargo from failing when running with multiple
processes (not tested).
http://gitweb.dragonflybsd.org/dragonfly.git/commitdiff/592912cde1dc358bf080ae9aff3eca491688f47c
https://github.com/rust-lang/libc/pull/643
> Change PTHREAD_STACK_MIN

- ports/net/ocserv/dragonfly/patch-src_tun.c
WARNING:
I have successfully built and installed this port with this patch,
but I haven't tested whether this port works well under DragonFly yet.
NOTE:
I have submitted this patch to the upstream, but no response yet.
> Fix net/ocserv by adding a patch

- special/Mk/diffs/Scripts_relative_link.sh.diff
Just ignore the flag and add a warning if any other flags would be passed.
No idea why would one want to strip when creating symlinks, but hey.
> special: Add support for -s in relative_link.sh wrapper.

- ports/devel/libpci/dragonfly/patch-lib_fbsd-device.c
Wit this patch, libpci will fall back to opening /dev/pci read-only, if the
user can't open it read-write, and it will then use the PCIOCGETCONF and
PCIOCGETBAR ioctls to retrieve information, instead of doing "raw" PCIOCREAD
and PCIOCWRITE ioctls.
This is needed to make the libpci usage in the chromium browser work
correctly.
> devel/libpci: Make basic functionality work without root privileges on DragonFly.

- ports/databases/redis/dragonfly/patch-src-config.h
This fix should build redis with kqueue instead of old select multiplexing api.
> databases/redis: added check for DragonFly to use kqueue.

- ports/databases/redis-devel/dragonfly/patch-src-config.h
- ports/databases/redis-devel/dragonfly/patch-src-lua_cjson.c
Fixed build when redis is  configured to use lua or luajit from dports.
Added checks for DragonFly to use kqueue multiplexing API instead of select.
> databases/redis-devel: added support of kqueue, fixed build with lua

- ports/devel/libudev-devd/dragonfly/patch-utils.c
> Fix libudev-devd for DragonFly. This is needed for the upcoming

- ports/graphics/wayland/newport/Makefile
* Add textproc/libxml2 and textproc/libxslt as dependencies.
Apologies!, it was not tested with synth. This time I ran 
% synth just-build graphics/wayland
with success. Will use synth in the future.
> Update graphics/wayland Makefile.

- ports/lang/guile2/Makefile.DragonFly
- ports/lang/guile2/STATUS
- ports/lang/guile2/dragonfly/patch-lib_signal.in.h
- ports/lang/guile2/dragonfly/patch-libguile_filesys.c
- ports/lang/guile2/dragonfly/patch-libguile_threads.c
synth test PASS
gmake check gives:
Totals for this test run:
passes:                 40824
failures:               1
unexpected passes:      0
expected failures:      9
unresolved test cases:  64
untested test cases:    1
unsupported test cases: 10
errors:                 6
> lang/guile2: Update patches on new version.

- ports/www/yarn/diffs/Makefile.diff
Before this patch, when calling "yarn", the following bug occurs:
> yarn
module.js:473
throw err;
^
Error: Cannot find module '/usr/home/lib/node_modules/yarn/bin/yarn.js'
at Function.Module._resolveFilename (module.js:527:15)
at Function.Module._load (module.js:453:25)
at Function.Module.runMain (module.js:665:10)
at startup (bootstrap_node.js:187:16)
at bootstrap_node.js:607:3
> This fixes yarn on DragonFly

- ports/devel/linux-kernel/Makefile.DragonFly
There is something strange, this fails to build with lang/gcc6-aux
over on video_mode.c -m16 with reg not being multiple of 8.
For now just use gcc 4.9.
> devel/linux-kernel: Prefer to build x86_64.

- ports/net/shadowsocks-libev/Makefile.DragonFly
The DragonFly-specific Makefile only disables the ``-Werror`` compiler flag, but it is no longer needed.
I've tested with the latest ``net/shadowsocks-libev`` (v3.1.0 from FreeBSD Ports) on DragonFly-5.1.
> net/shadowsocks-libev: Remove DragonFly-specific Makefile

- ports/graphics/inkscape/Makefile.DragonFly
The issue is fixed by adding "-Wl,-z,origin" to LDFLAGS.
> Fix the problem with graphics/inkscape not finding lib/inkscape_base.so

- ports/x11-drivers/xf86-video-scfb/dragonfly/patch-src_scfb__driver.c
This allows display powersaving to work, when running xf86-video-scfb on top of a drm kernel driver. The Display Powersaving doesn't work with a plain UEFI framebuffer.
> Add Display Powersaving support for xf86-video-scfb, via FBIO_BLANK ioctl.

- ports/security/krb5-116/dragonfly/patch-config_shlib.conf
- ports/security/krb5-116/dragonfly/patch-include_gssrpc_rpc.h
- ports/security/krb5-116/dragonfly/patch-include_krb5_krb5.hin
- ports/security/krb5-116/dragonfly/patch-lib_gssapi_generic_gssapi.hin
- ports/security/krb5-devel/dragonfly/patch-config_shlib.conf
- ports/security/krb5-devel/dragonfly/patch-include_gssrpc_rpc.h
- ports/security/krb5-devel/dragonfly/patch-include_krb5_krb5.hin
- ports/security/krb5-devel/dragonfly/patch-lib_gssapi_generic_gssapi.hin
Same patches apply to new version that was made deafult for krb5.
Synth test, make check passes
(in synth env had to create /etc/hosts file for local hostname lookup)
only one test fails:
./addrinfo-test -p telnet
getaddrinfo(hostname (null), service telnet,
hints { no-flags }):
error => servname not supported for ai_socktype
> security/krb5-116: Copy over the patches from krb5-115

- ports/math/octave-forge-video/Makefile.DragonFly
- ports/multimedia/x265/Makefile.DragonFly
- ports/multimedia/x265/diffs/Makefile.diff
Internal c++ implementation is safe enough, has its own X265_NS namespace
different calling argument order etc.
Avoids including -lmd and implicit -lcrypto as deps and unbreaks at least
math/octave-forge-video that uses ffmpeg libavcodec.so
While there, move most of the overrides from MF to MD
(except for extract args hack that should be done as patch: target).
Synth test passes, TestBench seems to be ok.
> multimedia/x265: Properly use internal bundled md5 c++ implementation.

- ports/net/isc-dhcp44-server/Makefile.DragonFly
Needed to find implicit -lssl.
> net/isc-dhcp44-server: Use localbase.

- ports/devel/ctags/dragonfly/patch-vim.c
This is a custom patch to our tree which helps our grok indexing. We can't submit it upstream because the project seems dead.
Maybe FreeBSD could benefit from it as well.
> Fix infinite loop when parsing VIM files

- ports/emulators/qemu/dragonfly/patch-disas_libvixl_vixl_utils.h
- ports/emulators/qemu/dragonfly/patch-hw-ppc_newworld.c
- ports/emulators/qemu/dragonfly/patch-hw_ppc_mac__oldworld.c
- Please note in order to build emulators/qemu, net/vde2 is required and this
only builds on latest master/release branches where the BIOCFEEDBACK ioctls
have been added.
> emulators/qemu - Fix build

- ports/net/p5-Socket6/dragonfly/patch-Socket6.xs
- ports/security/ike/Makefile.DragonFly
- ports/security/racoon2/Makefile.DragonFly
- ports/security/strongswan/Makefile.DragonFly
Mask out security/ ones.
The net/p5-Socket6 does not need the header.
> Adjust for IPSEC removal.

- ports/sysutils/areca-cli/Makefile.DragonFly
- ports/sysutils/hptcli/Makefile.DragonFly
- ports/sysutils/megacli/Makefile.DragonFly
- ports/sysutils/tw_cli/Makefile.DragonFly
Statically linked.
Reported-by: swildner
> Mask out FreeBSD binary ports for raids.

- ports/devel/9base/diffs/pkg-message.diff
- ports/java/openjdk7/diffs/pkg-message.diff
- ports/java/openjdk8/diffs/pkg-message.diff
- ports/mail/spamd/diffs/files_pkg-message.in.diff
- ports/shells/bash/diffs/files_pkg-message.in.diff
- ports/textproc/cdif/diffs/pkg-descr.diff
It was removed long ago and just confuses the users.
> Remove all references to fdescfs(5).

- ports/security/py-cryptography/dragonfly/patch-issue4168
Unblocks of all things - cmake.
Taken-from: HardenedBSD-ports
https://github.com/HardenedBSD/hardenedbsd-ports/commit/dcf62dd3
> security/py-cryptography: Add LibreSSL 2.7 support

- ports/security/py-cryptography/dragonfly/patch-issue4168
Unbreaks net-im/papyon when built against dports/security/openssl
> security/py-cryptography: Adjust for openssl.

- ports/x11-themes/plasma5-breeze/Makefile.DragonFly
The KF5-wayland is optional component.
Unbreaks x11-themes/plasma5-breeze-kde4 that uses its distfile.
> x11-themes/plasma5-breeze: Exclude wayland component.

- ports/net/freerdp/dragonfly/patch-libfreerdp_core_tcp.c
- ports/net/freerdp/dragonfly/patch-winpr_libwinpr_winsock_winsock.c
Just by running the 'xfreerdp' binary there is a segfault, the program is unusable. With the patches on this PR a RDP connection to a Windows 7 box can be established and seems usable.
> net/freerdp: Fix segfault on DragonFly

- ports/x11/i3status/dragonfly/patch-src_first__network__device.c
I've submitted two patches to i3status:
https://github.com/i3/i3status/pull/298 (merged)
https://github.com/i3/i3status/pull/299 (not reviewed/merged)
We'll need to remove the local patches for the next release that includes those PRs.
> x11/i3status: Fix interface type

- ports/devel/libcxxrt/newport/libcxxrt/Makefile
- ports/devel/libcxxrt/newport/libcxxrt/distinfo
- ports/devel/libcxxrt/newport/libcxxrt/pkg-descr
- ports/devel/libcxxrt/newport/libcxxrt/pkg-plist
- It will be used to build devel/libc++ which in turn will be used
to build newer chromium versions.
> devel/libcxxrt - Resurrect libcxxrt

- ports/emulators/qemu/Makefile.DragonFly
If built with gcc80 (which is the default now), qemu will SIGABRT
when booting from an ISO/IMG. There seems to be a bug which we can't
quite find yet so this is a workaround.
Note that when building with gcc50 we don't see this problem.
> emulators/qemu - Disable the stack protector for now.

- ports/net/freerdp/dragonfly/patch-CMakeLists.txt
Please note that this only fixes the build, it will not actually work since
it requires a waitable timer to work. There are several options:
1) Port deve/libepoll-shim to DragonFly (requires quite some work)
2) Have POSIX timers implemented in DragonFly (there is some work done already)
3) Implement InitializeWaitableTimer() with kevent(2)
We will likely go for option 3, this patch will make it easier to build and
test patches.
[ERROR][com.winpr.synch.timer] - InitializeWaitableTimer: os specific
implementation is missing
> net/freerdp - Fix build

- ports/devel/libvirt/dragonfly/patch-configure
- ports/devel/libvirt/dragonfly/patch-src_qemu_qemu__process.c
- ports/devel/libvirt/dragonfly/patch-src_util_virnetdevbridge.c
- Identify as freebsd in configure, too.
- To add a member to bridge(4) it has to be up.
Note: This requires dragonly master after commit baf84f0ae5e (Nov 5th 2018)
> devel/libvirt: Fix QEMU option

- ports/www/firefox/dragonfly/patch-ipc_chromium_src_base_shared__memory__posix.cc
For those who see a black screen after start up firefox 63.0,1 this patch should fix that. There are still SIGILL crashes all arround and we haven't figured out those yet.
> www/firefox: Adapt shm_open(3) call to DragonFly BSD

- ports/www/webkit-gtk2/Makefile.DragonFly
- Fixes a crash during startup for www/midori.
- Seen in: https://bugzilla.redhat.com/show_bug.cgi?id=1320240
> www/webkit-gtk2: Add -fno-delete-null-pointer-checks to CXXFLAGS

- ports/net-mgmt/collectd5/Makefile.DragonFly
- ports/net-mgmt/collectd5/diffs/pkg-plist.diff
- ports/net-mgmt/collectd5/dragonfly/patch-configure.ac
- ports/net-mgmt/collectd5/dragonfly/patch-src_cpu.c
- ports/net-mgmt/collectd5/dragonfly/patch-src_pf.c
- ports/net-mgmt/collectd5/dragonfly/patch-src_processes.c
- Disable unsupported plugins (zfs_arc, disk, tcpconns)
- Adjust configure.ac
- Rename procstat to collectd_proctstat
- Use SMP_MAXCPU to determine the maximum number of CPUs
- Use correct pfvar.h
- Implement processes plugin for dfly.
Once this PR (https://github.com/collectd/collectd/pull/3036) gets in we can remove most of our local patches.
> net-mgmt/collectd5 - Implement missing bits for DragonFly BSD

- ports/lang/libobjc2/dragonfly/patch-CMakeLists.txt
- ports/lang/libobjc2/dragonfly/patch-objcxx__eh.cc
- ports/lang/libobjc2/dragonfly/patch-objcxx__eh.h
- Commit 682717b from gnustep/libobjc2 from GitHub
- Only define type_info the typeinfo header is not included already.
- This is untested, only fixes the build.
> lang/libobjc2 - Fix build

- ports/graphics/weston/newport/Makefile
- ports/graphics/weston/newport/files/patch-clients_terminal.c
- ports/graphics/weston/newport/files/patch-src_compositor-drm.c
- ports/graphics/weston/newport/pkg-plist
* While there, also enable egl, i.e. accelerated rendering.
* And also remove appending the pci id to hw.dri.X.name. Since
recently both the radeon and i915 drivers set the hw.dri.0.busid
so we do not need the former. In addition, the call to setting
the former prevented using weston with the x11 backend. Lastly,
we are switching to using an ioctl to get the pci id, so both
sysctl-s will not be used any more.
> Fix weston build.

- ports/www/nginx-devel/dragonfly/patch-src_os_unix_ngx__file__aio__read.c
This patch has been upstreamed; and should be removed upon 1.15.9.
> nginx-devel: Unbreak building.

- ports/devel/meson/dragonfly/patch-messon
This should unbreak several things. We need to preserve rpaths
for compiler implicit things like -L/usr/lib/gcc80/ etc.
> devel/meson: Attempt to fix unconditional RUNPATH deletion.

- ports/devel/libevdev/newport/Makefile
- ports/devel/libevdev/newport/distinfo
- ports/devel/libevdev/newport/dragonfly/patch-tools_mouse-dpi-tool.c
- ports/devel/libevdev/newport/dragonfly/patch-tools_touchpad-edge-detector.c
- ports/devel/libevdev/newport/files/patch-libevdev_libevdev-uinput.c
- ports/devel/libevdev/newport/files/patch-test_test-libevdev-events.c
- ports/devel/libevdev/newport/files/patch-test_test-libevdev-has-event.c
- ports/devel/libevdev/newport/files/patch-test_test-libevdev-init.c
- ports/devel/libevdev/newport/files/patch-test_test-main.c
- ports/devel/libevdev/newport/pkg-descr
- ports/devel/libevdev/newport/pkg-plist
* Make devel/libevdev a DragonFly dport in order to rid
the port of libepoll-shim.
* Added two kqueue patches and deleted libepoll-shim dependency, 
but otherwise the port is identical with the FreeBSD port.
> Fix devel/libevdev build

- ports/devel/git-lfs/Makefile.DragonFly
- ports/devel/git-lfs/dragonfly/patch-lfshttp_certs_dragonfly.go
This port uses ronn(1) (from rubygem-ronn) to generate manpages, and ronn(1) further calls groff(1).  Therefore, need to add groff(1) to the build dependencies if the `MANPAGES` use flag is on.
Cheers,
Aaron
> Add devel/git-lfs port

- ports/security/tinc-devel/dragonfly/patch-src_bsd_device.c
- ports/security/tinc/dragonfly/patch-src_bsd_device.c
We don't create `/dev/tunX` or `/dev/tapX` anymore since commit https://github.com/DragonFlyBSD/DragonFlyBSD/commit/f1e9a4fff5aaac2be3a291dbfea94f94755991b8.  So update `security/tinc` and `security/tinc-devel` to use the auto-clone device `/dev/tun` or `/dev/tap` by default, which exists once the kernel module `if_tun` or `if_tap` is loaded.
Fixes https://github.com/DragonFlyBSD/DPorts/issues/213.
> security/tinc{,-devel}: Use '/dev/{tun,tap}' by default

- ports/sysutils/vpnc-scripts/dragonfly/patch-vpnc-script
* The `vpnc-script` script will add a route to `0.0.0.0/32`, and this causes the `get_default_gw()` function to return two gateways, which further causes the route deletion upon disconnect to fail.
Fix `get_default_gw()` function to return the correct gateway.
* Support DragonFly BSD in TUN creation and destroy.
* Fix TUN address deletion syntax for both IPv4 and IPv6.
This commit fixes issue #928 .
> sysutils/vpnc-scripts: Fix default route and support DragonFly

- special/Mk/diffs/bsd.commands.mk.diff
Fix a syntax error (encountered running `make -d g1 -rn` in
`/usr/dports`) in `bsd.commands.mk.diff` introduced a long time ago in
e87325a115e96880aa559578ceebd750a5ba059d, in what seems to have been an
attempt to cut down on verbosity.
The reverted code both allows the make debug graph to be printed and
expresses the intent of the test much better.
> Fix bsd.commands.mk syntax error

- ports/security/doas/diffs/Makefile.diff
Non-final manpages are now templates and contain @SUBSTSYSCONFDIR@
> Use correct manpages

- ports/net/gerbera/Makefile.DragonFly
* Gerbera requires C++17 filesystem feature, which is not available in
the base GCC 8.0.  Pull in the 'misc/cxxfs_gcc8' port to fix this
requirement.
* Switch the default UPnP library from libnpupnp to libupnp, because
libnpupnp (e.g., v4.1.5) fails to listen socket on DragonFly and thus
needs further fix; libupnp works well.
> Fix net/gerbera

- ports/security/py-nassl/Makefile.DragonFly
I ran [sample_client.py](https://github.com/nabla-c0d3/nassl/blob/release/sample_client.py) from upstream git repo and it worked, however during `dsynth test` i noticed a warning: 
```
actual-package-depends: dependency on /usr/lib/libcrypt.so not registered (normal if it belongs to base)
```
I'm not sure where it's coming from.
> security/py-nassl: Fix build phase

- ports/www/h2o/diffs/files_h2o.in.diff
- Running `service h2o configtest` fails as it does not find Perl.
- Running `/usr/local/etc/rc.d/h2o configtest` usually works as it has /usr/local/bin in PATH.
- FreeBSD is not affected as their /usr/sbin/service binary starts the h2o script with `env -L -/daemon`, which populates the env with those defined in /etc/login.conf for login class `daemon`, which happens to include /usr/local/bin in the PATH. This works, but is not really their intention, as /usr/local/etc/rc.d/h2o explicitly defines `h2o_perl` and should pass this as H2O_PERL environment variable!
> Fix `service h2o configtest`

- ports/mail/postfix-current/Makefile.DragonFly
from https://github.com/DragonFlyBSD/DPorts/issues/232
> mail/postfix-current : bring TLS option back

- ports/java/eclipse/Makefile.DragonFly
Reached [ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-director-plugin:3.0.0-SNAPSHOT:archive-products (archive-products) on project eclipse.platform.repository: Error packing product: Problem creating zip: Execution exception: Java heap space -> [Help 1]
I guess it will be hard to go further on my machine.
> java/eclipse : unbreak build phase by updating Makefile.DragonFly

- ports/sysutils/gkrellm2/dragonfly/patch-src_sysdeps_dragonfly.c
Fixes : https://bugs.dragonflybsd.org/issues/3301
> sysutils/gkrellm2 : change path to utmpx file

- ports/x11-drivers/xorgxrdp/Makefile.DragonFly
- ports/x11-drivers/xorgxrdp/diffs/pkg-plist.diff
otherwise xorg.conf end up in /etc/X11/xrdp as seen in the changes brought by https://github.com/neutrinolabs/xorgxrdp/commit/60afc114d936bbf8a5e4b9fb3ba3f8de59d07c39
> x11-drivers/xorgxrdp : use --use-strict-locations for configure phase

- ports/devel/llvm11/diffs/REMOVE
Remove patch which is only for LLDB
> devel/llvm11: Remove patch which is only for LLDB

- ports/sysutils/dmidecode/Makefile.DragonFly
On UEFI-only systems, the SMBIOS Entry Point structure must be located by the SMBIOS_TABLE_GUID configuration table, which is now exported via the 'hint.smbios.0.mem' following the FreeBSD's way.
Patch sysutils/dmidecode to use the kenv.
See also: https://github.com/DragonFlyBSD/DragonFlyBSD/commit/5e488df32cb01056a5b714a522e51c69ab7b4612
> sysutils/dmidecode: Emulate FreeBSD to support UEFI-only systems

- ports/graphics/spirv-tools/Makefile.DragonFly
decoration_manager.cpp:541 complains about being possibly uninitialized. However, it is initialized at line 540.
> graphics/spirv-tools: Use gcc12 and use -Wno-error=maybe-uninitialized

- ports/sysutils/py-psutil/dragonfly/patch-psutil___psutil__bsd.c
* Add cpu_count_cores() to list of symbols in _psutil_bsd.c.
Before:
>>> import psutil
>>> psutil.cpu_count()
8
>>> psutil.cpu_count(logical=True)
8
>>> psutil.cpu_count(logical=False)
Traceback (most recent call last):
File "<stdin>", line 1, in <module> File "/usr/local/lib/python3.9/site-packages/psutil/__init__.py", line 1591, in cpu_count ret = _psplatform.cpu_count_cores() File "/usr/local/lib/python3.9/site-packages/psutil/_psbsd.py", line 286, in cpu_count_cores return cext.cpu_count_cores() AttributeError: module 'psutil._psutil_bsd' has no attribute 'cpu_count_cores'
>>>
After:
>>> import psutil
>>> psutil.cpu_count()
8
>>> psutil.cpu_count(logical=True)
8
>>> psutil.cpu_count(logical=False)
4
>>>
> Fix crash when cpu_count() is called with logical=False.

- ports/net/minidlna/dragonfly/patch-monitor.c
The sparseness check function `check_notsparse()` isn't supported by DragonFly, and it caused the 'rescan' to not work; i.e., updated files were not indexed upon startup when the `-r` option was specified.
Just ignore the sparseness check to make the 'rescan' work as expected.
By the way, the `-r` option is recommended to add for minidlna; for example, add this to `/etc/rc.conf`:
```
minidlna_enable="YES"
minidlna_flags="-r"
```
> net/minidlna: Ignore sparseness check to make 'rescan' work

- ports/textproc/the_silver_searcher/dragonfly/patch-src_zfile.c
The `off64_t` type is unavailable on DragonFly BSD and thus causes the
building to fail.  Replace it with `z_off64_t`, which is properly
defined in `zconf.h` and is already included by this file.  So it should
be portable and a reasonable fix.
> textproc/the_silver_searcher: Add off64_t patch to fix building

- ports/x11-drivers/xf86-video-vesa/dragonfly/patch-src_vesa.c
DragonFlyBSD adoption of [this commit](https://github.com/freebsd/freebsd-ports/commit/b6d89731d542582d2cc751e7a56b78df76a38ce7)
> x11-drivers/xf86-video-vesa: adopt freebsd workaround

- ports/editors/neovim/dragonfly/patch-src_nvim_os_process.c
This patch updates the failed build of editors/neovim to allow it to build properly under the 2024Q3 branch in FreeBSD ports.
Apologies for the duplicate PR, I did not realize what I did to fix my branch would close the previous one.
> Updating editors/neovim to match 2024Q3 in FreeBSD ports

- ports/archivers/bzip3/Makefile.DragonFly
- ports/archivers/bzip3/dragonfly/patch-include_common.h
This patch removes the Makefile.DragonFly so the port will build, and modifies the 'include/common.h' file to allow for sucessfully building, installing, and running bzip3.
Port was tested by creating a bzip3 archive on a DragonFlyBSD machine and extracting it on a Linux machine with bzip3; then creating another bzip3 archive on Linux and extracting it using DragonFlyBSD, as well as the typical dsynth tests.
> This patch enables bzip3 as a port for DragonFlyBSD.

- ports/net/sacc/dragonfly/patch-ui__ti.c
This patch updates net/sacc to match the version on the 2024Q3 branch of FreeBSD's ports tree.
> Updating port for net/sacc

- ports/security/ca_root_nss/diffs/pkg-plist.diff
certctl is a in-base utility in FreeBSD that manages certificates and trust stores.  We don't have it and I don't think we current need to port it over, because we don't yet have /etc/openssl/certs and other trust stores.
See also: https://lists.dragonflybsd.org/pipermail/users/2025-May/452480.html
> security/ca_root_nss: Patch pkg-plist to not run certctl

- ports/x11-drivers/xf86-video-intel/dragonfly/patch-src_sna_kgem.c
__kgem_bo_map__cpu uses old version of I915_GEM_MMAP ioctl and is rejected by the i915 driver. It causes the xorg driver to fallback to memcpy'ing buffers, which is slow. Patch it to use newer version of ioctl.
> x11-drivers/xf86-video-intel: Fix gem mmap ioctl

- ports/x11-servers/xorg-server/dragonfly/patch-hw_xfree86_drivers_modesetting_driver.c
Intel i915 in master branch now supports hardware acceleration, bring back "AccelMethod" option to Xorg server, disabled by default for backwards compatibility.
> x11-servers/xorg-server: Re-enable glamor hw accel, disabled by default
