DragonFlyBSD/DeltaPorts

ports/www/chromium/dragonfly/patch-base__process__process_info_linux.cc
ports/www/chromium/dragonfly/patch-content__browser__time_zone_monitor_linux.cc
ports/www/chromium/dragonfly/patch-media__video__capture__fake_video_capture_device_factory.cc
ports/www/chromium/dragonfly/patch-media__video__capture__file_video_capture_device_factory.cc
ports/www/chromium/dragonfly/patch-media__video__capture__video_capture_device.cc
ports/www/chromium/dragonfly/patch-media__video__capture__video_capture_device.h
ports/www/chromium/dragonfly/patch-media__video__capture__video_capture_device_factory.cc
ports/www/chromium/dragonfly/patch-third_party__webrtc__base__systeminfo.cc

Several patches to fix the chromium port on DragonFly and FreeBSD.
I have also submitted them to freebsd-chromium: https://github.com/gliaskos/freebsd-chromium/pulls

Fix chromium

---

ports/astro/tclgeomap/Makefile.DragonFly
ports/cad/opencascade/Makefile.DragonFly
ports/databases/mysqltcl/Makefile.DragonFly
ports/devel/tbb/Makefile.DragonFly
ports/devel/tbb/dragonfly/patch-dragonfly_arch
ports/devel/tclvfs/Makefile.DragonFly
ports/devel/tclxml/Makefile.DragonFly
ports/graphics/togl/Makefile.DragonFly
ports/math/vtk6/Makefile.DragonFly
ports/net/tcludp/Makefile.DragonFly
ports/www/tdom/Makefile.DragonFly
ports/x11-toolkits/tix/Makefile.DragonFly
ports/x11-toolkits/tktable/Makefile.DragonFly
ports/x11-toolkits/tktray/Makefile.DragonFly

Several fixed dep ports for netgen.
Netgen currently kills X server.
Also several fixes for tcl configure scripts.

D1506 fix netgen

---

ports/astro/tkgeomap/Makefile.DragonFly
ports/audio/tclmidi/Makefile.DragonFly
ports/databases/tcl-sqlite3/Makefile.DragonFly
ports/databases/tdbc/diffs/Makefile.diff
ports/devel/tcl-memchan/Makefile.DragonFly
ports/devel/tclbsd/Makefile.DragonFly
ports/devel/tcllibc/diffs/Makefile.diff
ports/devel/tcloo/Makefile.DragonFly
ports/devel/tclthread/Makefile.DragonFly
ports/devel/yajl-tcl/Makefile.DragonFly
ports/lang/itcl4/Makefile.DragonFly
ports/lang/p5-Tcl/Makefile.DragonFly
ports/x11-toolkits/tkdnd/Makefile.DragonFly
ports/x11-toolkits/tktreectrl/Makefile.DragonFly

simple changes for compilation of Tk/Tcl

D1507 fix pack tcl tk

---

ports/devel/codeblocks/Makefile.DragonFly
ports/games/flightgear/Makefile.DragonFly
ports/graphics/gdtclft/Makefile.DragonFly
ports/graphics/vcg/Makefile.DragonFly
ports/multimedia/avidemux/Makefile.DragonFly
ports/multimedia/gstreamer1-plugins/Makefile.DragonFly
ports/security/yara/Makefile.DragonFly

Fix for flightgear included
multimedia/avidemux-plugins fails to build with mp4 format support

D1507 fix graphics

---

ports/x11/gmrun/dragonfly/patch-src_ci__string.h
ports/x11/gmrun/dragonfly/patch-src_gtkcompletionline.cc
ports/x11/gmrun/dragonfly/patch-src_main.cc
ports/x11/gmrun/dragonfly/patch-src_prefs.cc

Fix x11/gmrun

---

ports/games/freeminer/dragonfly/patch-src_CMakeLists.txt
ports/games/freeminer/dragonfly/patch-src_cguittfont_irrUString.h
ports/games/freeminer/dragonfly/patch-src_filesys.cpp
ports/games/freeminer/dragonfly/patch-src_guiChatConsole.cpp
ports/games/freeminer/dragonfly/patch-src_intlGUIEditBox.cpp
ports/games/freeminer/dragonfly/patch-src_porting.cpp
ports/games/freeminer/dragonfly/patch-src_porting.h

Connecting to servers, walking, sounds putting bricks works.
Everything else needs further testing.

games/freeminer: initial port

---

ports/devel/cargo/Makefile.DragonFly
ports/devel/cargo/diffs/distinfo.diff

Fixes https://github.com/DragonFlyBSD/DeltaPorts/pull/24

Add dependency on git and some minor cleanup

---

ports/audio/ccaudio2/Makefile.DragonFly
ports/devel/ccrtp/Makefile.DragonFly
ports/devel/commoncpp/Makefile.DragonFly
ports/devel/libzrtpcpp/Makefile.DragonFly
ports/devel/ucommon/Makefile.DragonFly

Few simple compile fixes, mostly alias.

D1509 add ucommon

---

ports/devel/loki/dragonfly/patch-src-Makefile
ports/devel/loki/dragonfly/patch-test_SingletonDll_Makefile

devel/loki: few simple makefile additions

---

ports/net-mgmt/pandorafms_console/Makefile.DragonFly
ports/net-mgmt/pandorafms_console/dragonfly/patch-include_ajax_events.php
ports/net-mgmt/pandorafms_console/dragonfly/patch-include_functions.php
ports/net-mgmt/pandorafms_console/dragonfly/patch-include_functions_snmp.php
ports/net-mgmt/pandorafms_console/dragonfly/patch-include_functions_snmp_browser.php
ports/net-mgmt/pandorafms_console/dragonfly/patch-install.php
ports/net-mgmt/pandorafms_console/dragonfly/patch-pandora_console_install
ports/net-mgmt/pandorafms_server/dragonfly/patch-Makefile.PL
ports/net-mgmt/pandorafms_server/dragonfly/patch-lib_PandoraFMS_Tool.pm
ports/net-mgmt/pandorafms_server/dragonfly/patch-pandora_server_installer
ports/net-mgmt/pandorafms_server/dragonfly/patch-util_recon_scripts_ipmi_recon.pl
ports/net-mgmt/pandorafms_server/dragonfly/patch-util_recon_scripts_snmp_recon.pl
ports/net-mgmt/pandorafms_server/dragonfly/patch-util_recon_scripts_wmi_recon.pl

Depends on sysutils/freeipmi.
Allows to build both server and client.
Untested but with php fixes should work on dragonfly too.

D1509 add pandorafms

---

ports/games/quadra/Makefile.DragonFly
ports/games/quadra/dragonfly/patch-skelton_include_dict.h
ports/games/quadra/dragonfly/patch-skelton_svgalib_video.cpp

No sound, "Audio write: Resource temporarily unavailable"
Other SDL based games have it too.

games/quadra: fix alloca.h and use nullptr

---

ports/comms/jsdr/Makefile.DragonFly
ports/comms/jsdr/dragonfly/patch-righandling_dabstick-dll_dabstick-dll.cpp
ports/devel/raknet/Makefile.DragonFly
ports/net/librdkafka/Makefile.DragonFly

D1509 alloca h pack

---

ports/graphics/xfig/dragonfly/patch-e_chop.c
ports/graphics/xfig/dragonfly/patch-fig.h
ports/graphics/xfig/dragonfly/patch-w_intersect.c
ports/graphics/xfig/dragonfly/patch-w_keyboard.c
ports/graphics/xfig/dragonfly/patch-w_snap.c

Port does gccdepend stage so patches are easier

graphics/xfig: simple alias by patch

---

ports/games/torcs/Makefile.DragonFly
ports/games/torcs/dragonfly/patch-src_libs_tgfclient_guifont.cpp
ports/games/torcs/dragonfly/patch-src_modules_simu_simuv2_SOLID-2.0_src_C_api.cpp

Why would USES+= alias be by default in port Makefile???

games/torcs: simple fix

---

ports/lang/ypsilon/dragonfly/patch-Makefile
ports/lang/ypsilon/dragonfly/patch-example_gtk_hello.scm
ports/lang/ypsilon/dragonfly/patch-sitelib_ffi.scm
ports/lang/ypsilon/dragonfly/patch-sitelib_ypsilon_ffi.scm
ports/lang/ypsilon/dragonfly/patch-sitelib_ypsilon_gl.scm
ports/lang/ypsilon/dragonfly/patch-sitelib_ypsilon_glut.scm

gmake check:
Passed all tests
Even OpenGL examples work.

lang/ypsilon: very simple initial port

---

ports/lang/yap/Makefile.DragonFly
ports/lang/yap/dragonfly/patch-H_dlmalloc.h
ports/lang/yap/dragonfly/patch-VC_include_Yap.h
ports/lang/yap/dragonfly/patch-clause_gcc5_build

While there add few missing __DragonFly__ checks

lang/yap: fix gcc5 build

---

ports/audio/vsound/Makefile.DragonFly
ports/cad/gplcver/Makefile.DragonFly
ports/devel/asl/Makefile.DragonFly
ports/games/edge/Makefile.DragonFly
ports/games/gtkevemon/dragonfly/patch-src_Makefile
ports/games/gtkevemon/dragonfly/patch-src_util_os.h
ports/games/jfsw/Makefile.DragonFly
ports/graphics/synaesthesia/Makefile.DragonFly
ports/misc/digitemp/dragonfly/patch-Makefile
ports/multimedia/lxdvdrip/Makefile.DragonFly
ports/multimedia/naludump/Makefile.DragonFly
ports/net-mgmt/cowpatty/dragonfly/patch-common.h
ports/net-p2p/zetacoin/Makefile.DragonFly
ports/net/latd/Makefile.DragonFly
ports/net/ndpi/Makefile.DragonFly
ports/sysutils/zbackup/Makefile.DragonFly

Few simple fixes, most of them tested for correctness

D1509 endian h pack

---

ports/benchmarks/smhasher/dragonfly/patch-Platform.cpp
ports/benchmarks/smhasher/dragonfly/patch-Platform.h

$ SMHasher
(No test hash given on command line, testing Murmur3_x86_32.)
-------------------------------------------------------------------------------
--- Testing Murmur3A (MurmurHash3 for x86, 32-bit)
[[[ Sanity Tests ]]]
Verification value 0xB0F57EE3 : Passed!
Running sanity check 1..........PASS
Running sanity check 2..........PASS
...

benchmarks/smhasher: simple affinity bypass

---

ports/math/vtk5/Makefile.DragonFly

Build:
math/vtk5
x11-toolkits/vtkfox

math/vtk5: add alias

---

ports/ftp/bftpd/dragonfly/patch-time.c

ftp/bftpd: fix build

---

ports/multimedia/lxdvdrip/Makefile.DragonFly
ports/net/coda6_server/Makefile.DragonFly

D1509 oops ver

---

ports/science/cdcl/Makefile.DragonFly

science/cdcl: expand OS detection

---

ports/lang/gauche/dragonfly/patch-gc_configure
ports/lang/gauche/dragonfly/patch-gc_dyn_load.c

make regression-tests:
Total: 14499 tests, 14498 passed,     1 failed,     1 aborted.
Single gauche--net.so test fails.

lang/gauce: small fix

---

ports/multimedia/libv4l/dragonfly/patch-utils_v4l2-compliance_v4l2-compliance.h

Include patch for multimedia/v4l-utils

multimedia/libv4l: fix ENODATA

---

ports/devel/cpp-netlib/dragonfly/patch-http_test_server.hpp

devel/cpp-netlib: undef MIN

---

ports/www/node/dragonfly/patch-deps_openssl_config_opensslconf.h

Bundled OpenSSL need verification

www/node: fix compile

---

ports/multimedia/libmovtar/Makefile.DragonFly

multimedia/libmovtar: try alias

---

ports/graphics/libosmesa/Makefile.DragonFly

For now this one will be slightly better

graphics/libosmesa: add libelf dep

---

ports/devel/gdb/Makefile.DragonFly
ports/devel/gdb/diffs/Makefile.diff
ports/devel/gdb/dragonfly/amd64dfly-nat.c
ports/devel/gdb/dragonfly/dfly-nat.c
ports/devel/gdb/dragonfly/dfly-nat.h
ports/devel/gdb/dragonfly/dfly64.mh
ports/devel/gdb/dragonfly/patch-gdb_Makefile.in

Once again I thrive on diffs.
Not a proper but allows to step through code.
"layout split" still able to display source too.
So if I didn't missed it should build and allow someone to finish the job.

devel/gdb: just to build

---

ports/math/clfft/dragonfly/patch-src_include_sharedLibrary.h

FFT OpenCL examples work great on i7-4712MQ

math/clfft: simple patch

---

ports/textproc/senna/Makefile.DragonFly

textproc/senna: try alias

---

ports/x11-toolkits/tile/Makefile.DragonFly

make test:
Tests ended at Sat Oct 03 16:32:03 EEST 2015
all.tcl:        Total   585     Passed  568     Skipped 17      Failed  0
Sourced 18 Test Files.

x11-toolkits/tile: simple tcl fix

---

ports/graphics/seom/Makefile.DragonFly

graphics/seom: use amd64 for yasm -m

---

ports/sysutils/deltup/dragonfly/patch-file.h

sysutils/deltup: simple fix

---

ports/mail/archiveopteryx-devel/Makefile.DragonFly
ports/mail/archiveopteryx/Makefile.DragonFly

Does not check CC, thus might as well..

mail/archiveopteryx: fix bare usage of clang

---

ports/net/slurm/dragonfly/patch-os.h
ports/net/slurm/dragonfly/patch-src_if_media.c

net/slurm: add missing __DragonFly__ defines

---

ports/www/quickie/Makefile.DragonFly
ports/www/quickie/dragonfly/patch-lib_quit.h

www/quickie: fix build

---

ports/multimedia/xvid/dragonfly/patch-configure

New version added few new target_os

multimedia/xvid: regen configure patch

---

ports/x11-themes/qtcurve/Makefile.DragonFly
ports/x11-themes/qtcurve/dragonfly/patch-lib_utils_color.h

This seems to be a proper one, all building combos pass.
If it fails again I give up.

x11-themes/qtcurve: deep patch

---

ports/net/wpa_gui/Makefile.DragonFly

Graphical wpa_gui starts.
Untested, ripped out my wifi cards from all laptops ;)

net/wpa_gui: fix build

---

ports/net/rtpproxy/Makefile.DragonFly
ports/net/rtpproxy/dragonfly/patch-src_rtp.h

net/rtpproxy: build fix

---

ports/net-mgmt/aircrack-ng/Makefile.DragonFly
ports/net-mgmt/aircrack-ng/dragonfly/patch-src_osdep_Makefile

Hi. This is related to https://github.com/DragonFlyBSD/DPorts/issues/164
Please read that for explanation

Fix aircrack-ng

---

ports/net/syncthing-discosrv/Makefile.DragonFly

This provides IsEOF,PunchHole methods?
Not a go programmer but should be enough.

net/syncthing-discosrv: use openbsd fileutil ext

---

ports/net/asterisk11/Makefile.DragonFly
ports/net/asterisk11/STATUS
ports/net/asterisk11/dragonfly/patch-Makefile.rules
ports/net/asterisk11/dragonfly/patch-chan_console.c
ports/net/asterisk11/dragonfly/patch-chan_skinny.c
ports/net/asterisk11/dragonfly/patch-chan_unistim.c
ports/net/asterisk11/dragonfly/patch-configure
ports/net/asterisk11/dragonfly/patch-include_asterisk_endian.h

Based on FreePBX Ports Collection

Fix asterisk-11.20.0 compilation

---

ports/games/minetest/dragonfly/patch-cmake_Modules_FindGettextLib.cmake
ports/games/minetest/dragonfly/patch-src_cguittfont_irrUString.h
ports/games/minetest/dragonfly/patch-src_porting.cpp
ports/games/minetest/dragonfly/patch-src_porting.h

Also try build:
games/minetest_game

games/minetest: add dragonfly and fix libintl detection

---

ports/games/libretro-cores/Makefile.DragonFly
ports/games/retroarch/Makefile.DragonFly
ports/games/retroarch/dragonfly/patch-qb_qb.system.sh

games/retroarch: add dragonfly

---

ports/devel/libx86/Makefile.DragonFly
ports/sysutils/vbetool/Makefile.DragonFly
ports/sysutils/vbetool/STATUS

Untested, but will be needed when i'll start playing with nv.

sysutils/vbetool: partially use alias

---

ports/games/darkplaces/Makefile.DragonFly
ports/games/darkplaces/dragonfly/patch-BSDmakefile
ports/games/darkplaces/dragonfly/patch-common.h
ports/games/darkplaces/dragonfly/patch-makefile
ports/games/darkplaces/dragonfly/patch-quakedef.h
ports/games/darkplaces/dragonfly/patch-sys_shared.c

I know, not pretty, but given how classic it is, this will do.
Tested on both backends: glx and sdl

games/darkplaces: add dragonfly, fix makefiles

---

ports/games/ember/Makefile.DragonFly
ports/games/ember/dragonfly/patch-configure

Missing media, w/ media in ~/.ember/ it runs fine.

games/ember: mark as broken

---

ports/devel/love5/dragonfly/patch-src_liblove_include_love_File.h

devel/love5: string => cstring

---

ports/games/freedink-data/Makefile.DragonFly

Drop -r argument for xargs in makefile
since engine core is already working and only data is missing.
Game works fine.
Also build:
games/freedink

games/freedink-data: fix xargs -r

---

ports/games/vegastrike-data/Makefile.DragonFly
ports/games/vegastrike/Makefile.DragonFly
ports/games/vegastrike/diffs/Makefile.diff
ports/games/vegastrike/dragonfly/patch-configure
ports/games/vegastrike/dragonfly/patch-src__vs_math.h
ports/games/vegastrike/dragonfly/patch-src_physics.h

Also fixed main Makefile
Game works, flying, laser shooting, sounds OK

games/vegastrike: Fix build, unignore data

---

ports/games/cultivation/dragonfly/patch-minorGems_system_endian.h

Some issues with dsp ioctl blocking

games/cultivation: fix build

---

ports/games/heretic/Makefile.DragonFly
ports/games/heretic/dragonfly/patch-musserv_musserver.h

There are few issues with audio(dsp ioctl blocks)

games/heretic: fix build

---

ports/games/briquolo/dragonfly/patch-src__MOGL__MOGL_EnsembleObjet.h
ports/games/briquolo/dragonfly/patch-src__MOGL__MOGL_GestionnaireObjet.h
ports/games/briquolo/dragonfly/patch-src__MOGL__MOGL_Objet.h
ports/games/briquolo/dragonfly/patch-src__MOGL__MOGL_Peau.h

Awesome arkanoid game with pretty graphics to kill the time.

games/briquolo: fix build

---

ports/games/kiki/dragonfly/patch-kodilib_src_tools_KFileTools.cpp

Damn my head is spinning, video+audio great.

games/kiki: fix d_reclen

---

ports/games/maelstrom/Makefile.DragonFly

games/maelstrom: fix install data path

---

ports/games/netradiant/Makefile.DragonFly
ports/games/netradiant/dragonfly/patch-tools_quake2_qdata_heretic2_common_threads.c

games/netradiant: fix build

---

ports/games/gtkradiant/Makefile.DragonFly
ports/games/gtkradiant/dragonfly/patch-SConstruct
ports/games/gtkradiant/dragonfly/patch-libs_typesystem.h

map editor, supports many game engines, but what a heap of a c--
GUI works thou

games/gtkradiant: fix build

---

ports/games/scorched3d/Makefile.DragonFly
ports/games/scorched3d/dragonfly/patch-configure-gl.m4

Think Worms3D but with tanks.
Game works perfectly.

games/scorched3d: add dragonfly

---

ports/games/nlarn/dragonfly/patch-Makefile

games/nlarn: add dragonfly lua version

---

ports/games/rtb/dragonfly/patch-Robots__seek_and_destroy__seek_and_destroy.cc
ports/games/rtb/dragonfly/patch-Robots__thomas2__thomas2.cc
ports/games/rtb/dragonfly/patch-Robots__xt-bot__xt-bot-a.cpp
ports/games/rtb/dragonfly/patch-Robots__xt-bot__xt-bot-b.cpp
ports/games/rtb/dragonfly/patch-src_Dialog.cc
ports/games/rtb/dragonfly/patch-src_Various.cc
ports/games/rtb/dragonfly/patch-team-framework__bots__cobra__cobra_clientspecificrepository.h
ports/games/rtb/dragonfly/patch-team-framework_io_unixinstreambuf.cpp
ports/games/rtb/dragonfly/patch-team-framework_io_unixoutstreambuf.cpp

Gui works, can select robots, arena is shown

games/rtb: fix build

---

ports/games/tsito/dragonfly/patch-src_Board.cpp

games/tsito: fix build

---

ports/games/q2p/dragonfly/patch-Makefile
ports/games/q2p/dragonfly/patch-qcommon__qcommon.h
ports/games/q2p/dragonfly/patch-unix__sh_unix.c

few issues with sound dsp blocks
few missing game data files

games/q2p: fix build

---

ports/games/d2x-xl/dragonfly/patch-include__ogl_defs.h

Game needs original game-data files to play

games/d2x-xl: fix build

---

ports/games/quake2max/Makefile.DragonFly
ports/games/quake2max/dragonfly/patch-Makefile

Few issues with dsp ioctl
Game needs original game data

games/quake2max: fix build

---

ports/games/r1q2/Makefile.DragonFly
ports/games/r1q2/dragonfly/patch-binaries_client_Makefile
ports/games/r1q2/dragonfly/patch-binaries_r1q2ded_Makefile

Few issues with dsp ioctl
GLX renderer unstable, needs further work

games/r1q2: add alias

---

ports/games/freedoko/Makefile.DragonFly
ports/games/freedoko/dragonfly/patch-Makefile.os
ports/games/freedoko/dragonfly/patch-src_Makefile.os

games/freedoko: add dragonfly

---

ports/games/q2pro/Makefile.DragonFly

Few issues with dsp ioctl
Game needs original game data

games/q2pro: add alias

---

ports/games/vultures-eye/Makefile.DragonFly

GUI for nethack works fine, both audio+video+mouse

games/vultures-eye: add alias

---

ports/games/species/dragonfly/patch-reproduction.hpp

Requires species.ini as input, so not sure how to test

games/species: fix build

---

ports/games/widelands/Makefile.DragonFly

Setlers like game, works fine on both radonsi and i915
Audio+video+mouse works.
Only 75 games to go through left.

games/widelands: add dragonfly

---

ports/games/tome4/Makefile.DragonFly
ports/games/tome4/dragonfly/patch-Makefile

While game compiles it might just need a working gamepad connected.
Since cannot test it and game is bigish ~350M just marking as broken.

games/tome4: mark as broken?

---

ports/games/burrtools/Makefile.DragonFly
ports/games/burrtools/diffs/Makefile.diff

games/burrtools: add missing OPSYS and few patches

---

ports/games/dangerdeep-data/Makefile.DragonFly
ports/games/dangerdeep-data/dragonfly/patch-trunk_r2035
ports/games/dangerdeep/Makefile.DragonFly
ports/games/dangerdeep/dragonfly/patch-SConstruct
ports/games/dangerdeep/dragonfly/patch-src_convoy.h
ports/games/dangerdeep/dragonfly/patch-src_faulthandler.h
ports/games/dangerdeep/dragonfly/patch-src_ptrlist.h
ports/games/dangerdeep/dragonfly/patch-src_ptrvector.h
ports/games/dangerdeep/dragonfly/patch-src_widget.cpp

WW2 U-boat simulator now works with glsl shaders too on haswell.

games/dangerdeep: fix build+ fix shaders

---

ports/games/fxsudoku/dragonfly/patch-build_configdetect

games/fxsudoku: add config target

---

ports/games/mudmagic/dragonfly/patch-bundled_libmxp_cmxpstate.cpp

Game works, fetching game lists too

games/mudmagic: add cstring for strcpy

---

ports/games/cheech/dragonfly/patch-src_cheechbot.cc
ports/games/cheech/dragonfly/patch-src_cheechd.cc
ports/games/cheech/dragonfly/patch-src_cheechwebd.cc

games/cheech: fix build

---

ports/games/bloodfrontier/dragonfly/patch-src_enet_unix.c

games/bloodfrontier: fix build

---

ports/games/blockout/dragonfly/patch-BlockOut_Http.cpp

Simple 3D tetris game works find, video+audio

games/blockout: fix build

---

ports/games/battletanks/dragonfly/patch-clunk_source.cpp

Simple kids-like 2D tanks game works fine

games/battletanks: fix build

---

ports/games/stonesoup/Makefile.DragonFly

games/stonesoup: add alias

---

ports/games/boswars/Makefile.DragonFly
ports/games/boswars/dragonfly/patch-SConstruct

too new libpng.
while:
pngcrush -fix -force old.png new.png
optipng -quiet -force -fix foo.png
would help, for now just marking as broken

games/boswars: mark as BROKEN

---

ports/games/ezquake/Makefile.DragonFly
ports/games/ezquake/dragonfly/patch-Makefile

Ugly port, low-res, needs original game data

games/ezquake: fix build

---

ports/games/glob2/dragonfly/patch-libgag_include_StreamBackend.h
ports/games/glob2/dragonfly/patch-libgag_src_FileManager.cpp

games/glob2: fix getc issue

---

ports/games/crrcsim/Makefile.DragonFly

Model airplane game works(video)

games/crrcsim: add alias

---

ports/games/digger-vgl/Makefile.DragonFly

games/digger-vgl: mark as ignored

---

ports/games/conquest/Makefile.DragonFly

games/conquest: mark as broken

---

ports/games/zatacka/Makefile.DragonFly

Not sure how to play it but gui works

games/zatacka: add alias

---

ports/games/xpipeman/Makefile.DragonFly

Use -DSYSV to avoid dereferencing FILE
Game works

games/xpipeman: fix build

---

ports/games/openjazz/dragonfly/patch-src_io_network.cpp

Game starts but requires original game data

games/openjazz: fix select in cpp

---

ports/games/epiar/Makefile.DragonFly
ports/games/epiar/dragonfly/patch-Source_Lua_src_Makefile

Space exploration game works, both video+audio

games/epiar: add dragonly

---

ports/games/oldrunner/patch-configure

games/oldrunner: fix configure

---

ports/games/teeworlds/dragonfly/patch-bam-0.4.0_src_platform.h
ports/games/teeworlds/dragonfly/patch-src_base_detect.h

This one has confusing build system. But yay buggers!
Worms style game, connecting to servers works, video+audio great.

games/teeworlds: add dragonfly

---

ports/games/xoj/Makefile.DragonFly

games/xoj: fix build

---

ports/games/dhewm3/dragonfly/patch-framework_minizip_ioapi.h

Game starts properly, just needs original game data

games/dhewm3: add dragonfly

---

ports/games/KnightCap/Makefile.DragonFly

Don't know how to prep coefs.dat file

games/KnightCap: fix build

---

ports/games/egl/Makefile.DragonFly
ports/games/egl/dragonfly/patch-makefile

games/egl: fix build

---

ports/games/doomlegacy/Makefile.DragonFly

If it ain't @nightmare it ain't right.
Doom1 works fine, video+audio+mouse

games/doomlegacy: add alias

---

ports/games/openglad/dragonfly/patch-src_parser.cpp

Segfaults on i3wm VM, DE should be fine

games/openglad: fix build

---

ports/games/chapping/dragonfly/patch-game_theme.cpp
ports/games/chapping/dragonfly/patch-library_controlmanager.cpp
ports/games/chapping/dragonfly/patch-library_timemanager.cpp

2D simple football( not a soccer you yankees! ) game works

games/chapping: fix build

---

ports/games/nehquake/Makefile.DragonFly

games/nehquake: add alias

---

ports/games/masterserver/dragonfly/patch-common.mk
ports/games/masterserver/dragonfly/patch-masterserver.c

games/masterserver: fix build

---

ports/games/evq3/Makefile.DragonFly
ports/games/evq3/dragonfly/patch-Makefile

games/evq3: fix build

---

ports/games/eduke32/Makefile.DragonFly

Very nasty port, maybe issues with ld.gold

games/eduke32: mark as broken

---

ports/games/qudos/Makefile.DragonFly
ports/games/qudos/dragonfly/patch-Makefile

games/qudos: fix build

---

ports/games/blokish/dragonfly/patch-src_piece.h

Game starts, few issues with widgets

games/blokish: fix build

---

ports/games/uqm/dragonfly/patch-build__unix__config_functions
ports/games/uqm/dragonfly/patch-build__unix__config_proginfo_build
ports/games/uqm/dragonfly/patch-build__unix__config_proginfo_host
ports/games/uqm/dragonfly/patch-src_libs_network_socket_socket_bsd.c
ports/games/uqm/dragonfly/patch-src_port.h

uch, this one took some time.
Classic game works, video+audio

games/uqm: add dragonfly

---

ports/games/wargus/dragonfly/patch-rip_music_unix.cpp

games/wargus: fix build

---

ports/games/xlogical/Makefile.DragonFly

games/xlogical: mark as broken

---

ports/games/tuxracer/dragonfly/patch-src_debug.c

games/tuxracer: fix build

---

ports/games/qtv/dragonfly/patch-qtv.h

Server ports get opened for streaming

games/qtv: add dragonfly

---

ports/games/pouetchess/dragonfly/patch-src_gui.h

games/pouetchess: fix build

---

ports/games/searchandrescue/dragonfly/patch-include__os.h
ports/games/searchandrescue/dragonfly/patch-include__xsw_ctype.h

Hely simulator works, both video+audio

games/searchandrescue: fix build

---

ports/games/xgalaga/Makefile.DragonFly

games/xgalaga: fix configure

---

ports/games/joequake/Makefile.DragonFly

games/joequake: mark as broken

---

ports/games/nethack32/Makefile.DragonFly

Fails to lock terminal, crashes

games/nethack32: mark as broken

---

ports/games/jfk/dragonfly/patch-src_lib_network.cc

Client part starts, starts waiting for server, has nice logo.
Server side needs configuration, thus untested.

games/jfk: fix build

---

ports/games/slashem-tty/Makefile.DragonFly

games/slashem-tty: mark broken

---

ports/games/sauerbraten/Makefile.DragonFly
ports/games/sauerbraten/dragonfly/patch-src_enet_unix.c

Cool CUBE2 based FPS shooter game works great on haswell
Note: quite big 655M installed

games/sauerbraten: fix build

---

ports/sysutils/p5-Quota/dragonfly/patch-Makefile.PL
ports/sysutils/p5-Quota/dragonfly/patch-Quota.xs
ports/sysutils/p5-Quota/dragonfly/patch-hints_bsd.h

sysutils/p5-Quota: fix build

---

ports/devel/p5-Algorithm-SVM/dragonfly/patch-bindings.h

devel/p5-Algorithm-SVM: fix build

---

ports/security/p5-Digest-Hashcash/patch-Hashcash.xs

Tests:
t/00_load.t .. ok
All tests successful.
Files=1, Tests=181,  1 wallclock secs ( 0.02 usr  0.00 sys +  0.25 cusr  0.02 csys =  0.29 CPU)
Result: PASS

security/p5-Digest-Hashcash: add dragonfly

---

ports/biology/p5-AcePerl/Makefile.DragonFly
ports/biology/p5-AcePerl/patch-acelib_wh_mydirent.h
ports/biology/p5-AcePerl/patch-acelib_wh_mystdlib.h

Tests timeout on remote server.

biology/p5-AcePerl: fix build

---

ports/devel/p5-Sys-MemInfo/dragonfly/patch-Makefile.PL
ports/devel/p5-Sys-MemInfo/dragonfly/patch-arch_dragonfly.xs

Tests PASS
I think i got swap bits ok, but haven't tested.
I'm "no swap" guy.

devel/p5-Sys-MemInfo: add dragonfly

---

ports/audio/csound6/Makefile.DragonFly

audio/csound6: add alias

---

ports/audio/csound/Makefile.DragonFly
ports/audio/csound/diffs/Makefile.diff

GUI starts, utilities can run.

audio/csound: fix build

---

ports/irc/gseen.mod/Makefile.DragonFly
ports/irc/gseen.mod/dragonfly/patch-configure

just like eggdrop, just extra TAR

irc/gseen.mod: add dragonfly

---

ports/graphics/mitsuba/Makefile.DragonFly

Uncriple x86_64 builds with GCC.
GUI works, TUI too.

graphics/mitsuba: fix build

---

ports/science/gnudatalanguage/dragonfly/patch-src__basic_fun.cpp
ports/science/gnudatalanguage/dragonfly/patch-src__dinterpreter.hpp
ports/science/gnudatalanguage/dragonfly/patch-src__file.cpp

gdl TUI works.
No errors in:
make regression-test MAINTAINER_MODE=yes

science/gnudatalanguage: add dragonfly

---

ports/japanese/man/Makefile.DragonFly

playing with LANG, LC_CTYPE does print something.

japanese/man: add alias

---

ports/math/surf/dragonfly/patch-configure

math/surf: add dragonfly threads

---

ports/math/crlibm/dragonfly/patch-configure

make regression-test:
All 21 tests passed

math/crlibm: add dragonfly

---

ports/math/drgeo/dragonfly/patch-drgeo_adaptDialog.cc

GUI works, opening examples too.

math/drgeo: fix build

---

ports/games/cataclysm-dda/Makefile.DragonFly

ncurses backend game works (thou no sound as per Makefile desc).
SDL untested, cause port is very ... you know

games/cataclysm-dda: fix build

---

ports/devel/smake/diffs/Makefile.diff
ports/devel/smake/dragonfly/patch-lib_getexecpath.c

devel/smake: fix build

---

ports/graphics/blender/Makefile.DragonFly
ports/graphics/blender/diffs/pkg-plist.diff
ports/graphics/blender/dragonfly/patch-extern_Eigen3_Eigen_src_Core_util_Memory.h
ports/graphics/blender/dragonfly/patch-extern__libmv__libmv__base__aligned_malloc.cc
ports/graphics/blender/dragonfly/patch-extern__libmv__libmv__numeric__numeric.h
ports/graphics/blender/dragonfly/patch-extern__libmv__third_party__glog__src__config.h
ports/graphics/blender/dragonfly/patch-extern__libmv__third_party__glog__src__logging.cc
ports/graphics/blender/dragonfly/patch-intern__cycles__util__util_aligned_malloc.cpp
ports/graphics/blender/dragonfly/patch-intern__guardedalloc__intern__mallocn.c
ports/graphics/blender/dragonfly/patch-intern__guardedalloc__intern__mallocn_intern.h
ports/graphics/blender/dragonfly/patch-source_creator_creator.c

BMW v27 performance test is much better.
Even game engine is almost usable.

graphics/blender: update to 2.76b version

---

ports/benchmarks/super-smack/dragonfly/patch-src_client.cc
ports/benchmarks/super-smack/dragonfly/patch-src_dictionary.h

benchmarks/super-smack: fix build, add dragonfly

---

ports/benchmarks/dkftpbench/dragonfly/patch-Platoon.h

benchmarks/dkftpbench: fix build

---

ports/x11/bbrun/Makefile.DragonFly

x11/bbrun: add alias

---

ports/devel/py-bison/dragonfly/patch-setup.py

Tests:
$ python -c "import bison" && echo $?
0

devel/py-bison: add dragonfly

---

ports/net/ngrep/Makefile.DragonFly
ports/net/ngrep/dragonfly/patch-configure

ngrep runs:
//# ngrep
interface: re0 (192.168.0.0/255.255.255.0)
? 192.168.0.1 -> 224.0.0.18
!d........................
? 192.168.0.1 -> 224.0.0.18
!d........................

net/ngrep: fix build

---

ports/misc/ytree/Makefile.DragonFly

misc/ytree: fix build

---

ports/textproc/rtfx/dragonfly/patch-src_usuals.h

textproc/rtfx: add cstring

---

ports/textproc/aiksaurus/dragonfly/patch-gtk_src_Display.h
ports/textproc/aiksaurus/dragonfly/patch-gtk_src_gtkAiksaur.t.cpp

GUI works, words can be looked up.

textproc/aiksaurus-gtk: fix build

---

ports/print/html2latex/dragonfly/patch-HTMLparse.c
ports/print/html2latex/dragonfly/patch-html2latex.c

Utility converts pages to .tex fine.

print/html2latex: fix build

---

ports/x11/3ddesktop/dragonfly/patch-config.hpp

3D desktop swithing even works with my i3wm.

x11/3ddesktop: fix build

---

ports/devel/pysvn/dragonfly/patch-setup_configure.py

devel/pysvn: add dragonfly

---

ports/graphics/xpaint/dragonfly/patch-rw_rwTable.c

graphics/xpaint: add dragonfly

---

ports/lang/fpc-utils/dragonfly/patch-utils_fpcres_fpmake.pp
ports/lang/fpc-utils/dragonfly/patch-utils_fppkg_fpmake.pp
ports/lang/fpc-utils/dragonfly/patch-utils_instantfpc_fpmake.pp

Just enough to keep make check-plist happy

lang/fpc-utils: add dragonfly

---

ports/games/doomsday/Makefile.DragonFly

games/doomsday: fix build

---

ports/archivers/par2cmdline-tbb/Makefile.DragonFly

make check PASS, once chmod +x the test cases

archivers/par2cmdline-tbb: fix build

---

ports/deskutils/hot-babe/dragonfly/patch-hot-babe.c

Motivational desk util, great for troubleshooting parallel builds.

deskutils/hot-babe: fix load monitors

---

ports/net/dpinger/Makefile.DragonFly

net/dpinger: fix build

---

ports/graphics/rawtherapee/diffs/Makefile.diff
ports/graphics/rawtherapee/dragonfly/patch-rtengine_improcfun.h

GUI works, don't have any RAW images handy right now,
but everything seems right. OpenMP and RUN_PATH:
Library runpath: [/usr/lib/gcc50:/usr/local/lib]

graphics/rawtherapee: uncriple the build

---

ports/devel/love/dragonfly/patch-src_common_config.h

LUA-JIT dependency needs recheck by someone w/ lua knowledge.
GUI starts and works, but prone to segfault in lua.so upon exit.

devel/love: fix build after version bump

---

ports/graphics/panomatic/dragonfly/patch-zthread_include_zthread_Config.h

graphics/panomatic: add dragonfly

---

ports/textproc/gmetadom/dragonfly/patch-src__gdome_cpp_smart__include__GdomeSmartDOMTraits.hh
ports/x11-toolkits/gtkmathview/Makefile.DragonFly
ports/x11-toolkits/gtkmathview/dragonfly/patch-src_common_String.hh

MathML xml .ps/.svg generation and viewer work.

x11-toolkits/gtkmathview: fix build

---

ports/devel/bisoncpp/Makefile.DragonFly
ports/devel/libbobcat/Makefile.DragonFly

devel/bisoncpp: fix build

---

ports/multimedia/atomicparsley/Makefile.DragonFly

Also try building: audio/audiotag

multimedia/atomicparsley: fix typo

---

ports/graphics/darknock/Makefile.DragonFly
ports/graphics/darknock/dragonfly/patch-src_net_maxnet.cpp
ports/graphics/darknock/dragonfly/patch-src_net_node.cpp
ports/graphics/darknock/dragonfly/patch-src_net_pattern.h

GUI works, filters too.
Can tune edges finders.

graphics/darknock: fix build and runtime

---

ports/graphics/gimmage/dragonfly/patch-src_FileManager.h

graphics/gimmage: fix strcpy

---

ports/graphics/iiview/dragonfly/patch-compat.c
ports/graphics/iiview/dragonfly/patch-compat.h

Very small and useful image browser that has TUI in GUI
to browse through dirs and view images.

graphics/iiview: don't use compat on DragonFly

---

ports/sysutils/webmin/dragonfly/patch-mount__freebsd-mounts-7.c

Conditionalize MNT_UNION support.

sysutils/webmin: fix build

---

ports/graphics/iccexamin/Makefile.DragonFly
ports/graphics/iccexamin/dragonfly/patch-configure
ports/graphics/oyranos/Makefile.DragonFly

iccexamin GUI works, even 3D gamut inspect tool
oyranos has issue in distrib elektra (kdb.h header conflict w/ krb5)
TESTS:
Tests with status SUCCESS: 7
Tests with status FAIL: 0
Tests with status XFAIL: 2
Tests with status SYSERROR: 0
Tests with status UNKNOWN: 0
Tests SUCCEEDED

graphics/iccexamin: fix build issues

---

ports/graphics/cinepaint/Makefile.DragonFly

Some not so prety workarounds but GUI works.
Since it is final product explict -lblah++ will not hurt.

graphics/cinepaint: fix build issues

---

ports/graphics/xfractint/Makefile.DragonFly

Awesome interactive fractal viewer.

graphics/xfractint: add alias

---

ports/graphics/dcp2icc/Makefile.DragonFly

graphics/dcp2icc: fix unzip extract issue, add alias

---

ports/graphics/metacam/dragonfly/patch-metatiff.h

graphics/metacam: fix build

---

ports/devel/9base/dragonfly/patch-lib9_dirfwstat.c
ports/devel/9base/dragonfly/patch-lib9_dirread.c
ports/devel/9base/dragonfly/patch-lib9_u.h

Few alternative plan9 utilities under /usr/local/9/bin

devel/9base: add dragonfly

---

ports/devel/nspr/dragonfly/patch-pr_tests_Makefile.in

Unbreaks build with DEVELOPER=yes

devel/nspr: fix build w/ TEST option

---

ports/games/stonesoup/Makefile.DragonFly

Likely could be expanded in fports/Makefile.
Both default and -sdl versions work.

games/stonesoup: add std to cflags

---

ports/science/gnudatalanguage/dragonfly/patch-src__basic_fun.cpp
ports/science/gnudatalanguage/dragonfly/patch-src__dinterpreter.hpp
ports/science/gnudatalanguage/dragonfly/patch-src__file.cpp

science/gnudatalanguage: regen patches

---

ports/security/cryptlib/Makefile.DragonFly
ports/security/cryptlib/dragonfly/patch-makefile
ports/security/cryptlib/dragonfly/patch-misc_debug.h
ports/security/cryptlib/dragonfly/patch-random_unix.c

both testlib,stestlib test programs fail on expired certificate.
security/p5-PerlCryptLib: gmake test:
t/1.t .. ok
t/2.t .. ok
All tests successful.
Files=2, Tests=33,  0 wallclock secs ( 0.04 usr  0.02 sys +  0.20 cusr  0.32 csys =  0.58 CPU)
Result: PASS

security/cryptlib: some fixes

---

ports/devel/p5-Sys-Info-Base/dragonfly/patch-lib_Sys_Info_Constants.pm
ports/devel/p5-Sys-Info-Driver-BSD/dragonfly/patch-SPEC
ports/devel/p5-Sys-Info-Driver-BSD/dragonfly/patch-lib_Sys_Info_Driver_BSD_OS.pm
ports/sysutils/p5-BSD-Sysctl/dragonfly/patch-Makefile.PL
ports/sysutils/p5-BSD-Sysctl/dragonfly/patch-Sysctl.xs
ports/sysutils/p5-BSD-Sysctl/dragonfly/patch-t_01-get.t

Rebuild order:
sysutils/p5-BSD-Sysctl
devel/p5-Sys-Info-Base
devel/p5-Sys-Info-Driver-BSD
devel/p5-Sys-Info
Sample script and output:
http://sprunge.us/WWUE

D1601 fix p5 sys info

---

ports/audio/gigedit/Makefile.DragonFly
ports/audio/linuxsampler/dragonfly/patch-src_common_atomic.h
ports/audio/linuxsampler/dragonfly/patch-src_drivers_audio_AudioChannel.cpp

Fixes build and runtime:
audio/linuxsampler (TUI)
audio/gigedit (GUI-GTKMM)
audio/qsampler (GUI-QT)

D1601 add gigedit

---

ports/audio/pms/dragonfly/patch-src_pms.cpp
ports/audio/pms/dragonfly/patch-src_pms.h

audio/pms: fix build

---

ports/audio/yell/Makefile.DragonFly

audio/yell: mark as ignored

---

ports/audio/grip/Makefile.DragonFly

GUI starts, but to be functional needs DBUS

audio/grip: add alias

---

ports/audio/cmp3/dragonfly/patch-cmp3.h

audio/cmp3: fix build

---

ports/mail/postsrsd/dragonfly/patch-srs2.c

mail/postsrsd: fix alloca.h case

---

ports/x11-fm/gentoo/dragonfly/patch-src__cfg_paths.c
ports/x11-fm/gentoo/dragonfly/patch-src__mntent_wrap.c
ports/x11-fm/gentoo/dragonfly/patch-src_gentoo.h

Untested: dbus, but should work

x11-fm/gentoo: fix build

---

ports/audio/audacity/Makefile.DragonFly
ports/audio/audacity/dragonfly/patch-src_BlockFile.cpp
ports/audio/audacity/dragonfly/patch-src_effects_nyquist_Nyquist.cpp

audio/audacity: new version new cxx patches

---

ports/devel/kdesvn-kde4/dragonfly/patch-src_svnfrontend_svnactions.cpp
ports/devel/kdesvn-kde4/dragonfly/patch-src_svnqt_path.cpp
ports/devel/kdesvn-kde4/dragonfly/patch-src_svnqt_path.h

devel/kdesvn-kde4: regen patches

---

ports/japanese/lipsf/Makefile.DragonFly

japanese/lipsf: fix ncurses

---

ports/misc/iselect/Makefile.DragonFly

Version with ports ncurses works

misc/iselect: fix ncurses

---

ports/net-im/uTox/Makefile.DragonFly

This one will likely need full DragonFly target soon,
so small/quick one first.

net-im/uTox: fix new version

---

ports/sysutils/devedid-data/newport/Makefile
ports/sysutils/devedid-data/newport/files/regen-firmware.sh
ports/sysutils/devedid-data/newport/files/remove-firmware.sh
ports/sysutils/devedid-data/newport/pkg-deinstall.fw
ports/sysutils/devedid-data/newport/pkg-install.fw
ports/sysutils/devedid-data/newport/pkg-plist

To generate and install monitor edid fw to /boot/modules.local

sysutils/devedid-data: Update to use wrap-fw_module.sh

---

ports/textproc/asciinema/dragonfly/patch-Godeps___workspace_src_github.com_creack_termios_raw_termios__32.go
ports/textproc/asciinema/dragonfly/patch-Godeps___workspace_src_github.com_creack_termios_raw_tioc__bsd.go
ports/textproc/asciinema/dragonfly/patch-Godeps___workspace_src_github.com_kr_pty_pty__dragonfly.go
ports/textproc/asciinema/dragonfly/patch-Godeps___workspace_src_github.com_kr_pty_pty__unsupported.go
ports/textproc/asciinema/dragonfly/patch-Godeps___workspace_src_github.com_kr_pty_types__dragonfly.go
ports/textproc/asciinema/dragonfly/patch-Godeps___workspace_src_github.com_kr_pty_ztypes__dragonfly__amd64.go
ports/textproc/asciinema/dragonfly/patch-util_fdset_dragonfly_amd64.go
ports/textproc/asciinema/dragonfly/patch-util_select.go

Fix pty-related code of asciinema for DragonFly

---

ports/graphics/osgearth/dragonfly/patch-src_osgEarth_FileUtils.cpp

Build fix, can't test runtime at this time.

graphics/osgearth: Use stat on dragonfly

---

ports/emulators/qemu-devel/dragonfly/patch-disas_libvixl_vixl_utils.h
ports/emulators/qemu-devel/dragonfly/vknet-patch

qemu-system-x86_64 works, not sure about vknet

emulators/qemu-devel: fix build on new version

---

ports/sysutils/gkrellm2/Makefile.DragonFly
ports/sysutils/gkrellm2/dragonfly/patch-src_sysdeps_dragonfly.c

Seems that dragonfly got official support.
Added coretemp temparature sensors (in a dodgy way for now)
Some strangeness w/ mem stats, but rest is somewhat +/- functional.

sysutils/gkrellm2: Fix build on new version

---

ports/sysutils/wuzzah/dragonfly/patch-common.h

Small sneaky little program, just errno decl issue.
Could add string.h fto strlen() but works without it.

sysutils/wuzzah: Add to collection

---

ports/security/please/dragonfly/patch-please.c

Tested with user in wheel group: please rm -rf /
it worked!

security/please: Add to collection.

---

ports/devel/duplo/dragonfly/patch-Duplo.cpp

Small dup lines dectecting program.
Takes file list in a provided file.

devel/duplo: Add to collection.

---

ports/x11-wm/bbpager/dragonfly/patch-src_Baseresource.cxx
ports/x11-wm/bbpager/dragonfly/patch-src_main.cxx
ports/x11-wm/bbpager/dragonfly/patch-src_resource.cxx

Provide protos for strcmp, strcasecmp

x11-wm/bbpager: Build fix.

---

ports/www/h2o/Makefile.DragonFly
ports/www/h2o/dragonfly/patch-lib_common_socket_evloop.c.h

www/h2o: Fix build

---

ports/www/node5/Makefile.DragonFly

www/node5: Mark as ignored.

---

ports/chinese/ibus-libpinyin/dragonfly/patch-src_PYLibPinyin.cc

A bit sensitive to changes in deps, but lets check where it gets us.

chinese/ibus-libpinyin: Fix getline issue

---

ports/devel/gearmand-devel/Makefile.DragonFly
ports/devel/gearmand-devel/dragonfly/patch-configure
ports/devel/gearmand-devel/dragonfly/patch-libtest_main.cc

Same patches as non devel package so there is no point
in keeping it failing.

devel/gearmand-devel: Fix devel package.

---

ports/emulators/desmume/dragonfly/patch-configure.ac

desmume-glade starts the GUI, everything seems to be working.

emulators/desmume: Add Dragonfly to HOST_BSD

---

ports/emulators/hercules/Makefile.DragonFly
ports/emulators/hercules/dragonfly/patch-configure

Emulator seems to be initing and running, just not sure
how to setup config files.

emulators/hercules: Fix build.

---

ports/emulators/fceux/dragonfly/patch-src_utils_ioapi.h

Only synth test tested, reason gtk3->dbus

emulators/fceux: Simple build fix.

---

ports/emulators/darcnes/Makefile.DragonFly

emulators/darcnes: Use alias.

---

ports/emulators/kcemu/dragonfly/patch-configure

TUI works, but not familiar how to setup the rom/profiles thingies.

emulators/kcemu: Use freebsd target.

---

ports/emulators/ucon64/Makefile.DragonFly

Will get broken on any update so not worth it.

emulators/ucon64: Marks as ignored.

---

ports/emulators/fs-uae/dragonfly/patch-common.mk

This amiga 500 emulator works great in GUI mode.
To exit use F12+Q

emulators/fs-uae: Fix gmake->make issue.

---

ports/emulators/hugo/Makefile.DragonFly

GUI starts, don't have roms to test it.

emulators/hugo: Use SDL_FREEBSD.

---

ports/net/czmq/Makefile.DragonFly
ports/net/czmq/dragonfly/patch-configure.ac
ports/net/czmq/dragonfly/patch-include_czmq_prelude.h

Smth with certificate creation.
makecert creates certificates.

net/czmq: Alias to freebsd

---

ports/net/wmwlmon/Makefile.DragonFly

While it could compile, I doubt that it would function correctly.

net/wmwlmon: Make as broken

---

ports/dns/adsuck/Makefile.DragonFly

There are better alternatives.

dns/adsuck: Mark as ignored

---

ports/deskutils/sliderule/dragonfly/patch-xcalc.c

GUI with ruler from the school times starts and works as intended.

deskutils/sliderule: Fix thread errno linakge

---

ports/devel/paexec/dragonfly/patch-paexec_tasks.c

devel/paexec: Terminate RB_* stuff.

---

ports/dns/libdjbdns/dragonfly/patch-error.h

dns/libdjbdns: Fix thread errno

---

ports/www/sams2/dragonfly/patch-plugins_fsusage_getfsusage.cpp

www/sams2: Fix build, UINTMAX_MAX issue

---

ports/editors/the/Makefile.DragonFly

Ncurses window works, has strange controls.

editors/the: Add depend on ncurses

---

ports/devel/avarice/Makefile.DragonFly

No point of having it, hard to fix.

devel/avarice: Mark as ignored.

---

ports/x11-wm/gcompmgr/dragonfly/patch-src_params.cc
ports/x11-wm/gcompmgr/dragonfly/patch-src_params.h
ports/x11-wm/gcompmgr/dragonfly/patch-src_stdxinc.h

GUI to config parameters starts and seems to be working.

x11-wm/gcompmgr: Fix c in not c + ps invoke

---

ports/games/xrobots/Makefile.DragonFly

games/xrobots: Disable score locking

---

ports/lang/tcl87/dragonfly/patch-unix_configure

Will help to ensure that nothing got broken when
it will become default version will happen.

lang/tcl87: Fix devel package

---

ports/textproc/tokyodystopia/Makefile.DragonFly
ports/textproc/tokyodystopia/dragonfly/patch-myconf.h

Was missing LDFLAGS, myconf.h is cosmetical.
Not sure how to test it, but should be ok

textproc/tokyodystopia: Fix build

---

ports/news/nn/Makefile.DragonFly

gcc -P for cpp usage, thread errno and ncurses
Program seems should be working correctly, but i'm not
changing my hostname just to test it:
[rw@_ ~]$ hostname
_
[rw@_ ~]$ nn
hostname=_, You need a fully qualified domain name

news/nn: Fix build blockers

---

ports/x11-toolkits/wmapp/dragonfly/patch-wmapp.cc
ports/x11-toolkits/wmapp/dragonfly/patch-wmwindow.cc

Only lib is available, not tested

x11-toolkits/wmapp: Fix c in not c

---

ports/net/wmnetload/dragonfly/patch-configure

wmnetload -i re0 -w -bl
works and displays small square with interface rates as digital clock

net/wmnetload: Alias to freebsd

---

ports/polish/trf/Makefile.DragonFly

polish/trf: Fix build

---

ports/www/anyterm/Makefile.DragonFly

$ anytermd -c /usr/local/bin/bash -p 6969 --local-only
and web shell on firefox works great!

www/anyterm: Fix build

---

ports/sysutils/nvclock/Makefile.DragonFly

Lets for now not give users a funny ideas.

sysutils/nvclock: Mark as skipped

---

ports/lang/yorick/Makefile.DragonFly

lang/yorick: Fix exp10 misdetection

---

ports/science/ncs/Makefile.DragonFly

Just got to dep of py27-qt4 and decided to try on muscles

science/ncs: Try fix

---

ports/news/nntp/Makefile.DragonFly
ports/news/nntp/dragonfly/patch-xfer_nntpxfer.c
ports/news/nntp/dragonfly/patch-xmit_get_tcp_conn.c
ports/news/nntp/dragonfly/patch-xmit_remote.c

Very old package w/ lots of problems but it compiled.
p.s. there is pkg-plist problem but thats another story

news/nntp: Fix build

---

ports/textproc/2bsd-diff/Makefile.DragonFly
ports/textproc/2bsd-diff/dragonfly/patch-diffdir.c

Utility works on both files and dirs

textproc/2bsd-diff: Fix d_reclen

---

ports/games/gnake/Makefile.DragonFly

games/gnake: Add uses ncurses

---

ports/games/xmris/Makefile.DragonFly

games/xmris: Use alias

---

ports/games/eif/Makefile.DragonFly
ports/games/eif/dragonfly/patch-src_games.c

games/eif: Fix build

---

ports/editors/jed/Makefile.DragonFly

editors/jed: Use alias

---

ports/misc/viz/dragonfly/patch-loadfile.c

Utility works, converts invisible tabs to \t

misc/viz: Fix thread errno

---

ports/sysutils/memdump/Makefile.DragonFly

Dangerous utility! For experienced users.

sysutils/memdump: Add DragonFly to supported

---

ports/devel/pcc-libs/Makefile.DragonFly
ports/devel/pcc-libs/dragonfly/patch-configure
ports/lang/pcc/dragonfly/patch-os_dragonfly_ccconfig.h

Since they finaly were added to freebsd-ports, now include dragonfly too.
Simple hello world .c works fine.

lang/pcc: Hook pcc-libs

---

ports/graphics/weston/newport/files/patch-src_compositor-drm.c

This is needed for the PCI busid to be appended to the hw.dri.X.name
sysctl node, which will be needed for the accelerated gl-renderer backend
to work properly.

graphics/weston: Call drmSetInterfaceVersion in drm backend initialization.

---

ports/multimedia/libmediaart/diffs/pkg-plist.diff

Noticed that fails in synth test

multimedia/libmediaart: Fix plist

---

ports/x11-wm/blackbox/Makefile.DragonFly

port has .la files, and synth is unhappy w/o libtool
noticed while testing mail/bbmail

x11-wm/blackbox: Fix stage Q/A

---

ports/ports-mgmt/dialog4ports/Makefile.DragonFly
ports/ports-mgmt/dialog4ports/diffs/Makefile.diff

No functional change to non-static version

ports-mgmt/dialog4ports-static: Try to fix static lib

---

ports/devel/jsl/Makefile.DragonFly
ports/sysutils/uefi-edk2-bhyve/Makefile.DragonFly
ports/www/csstidy/Makefile.DragonFly

fix recent broken patches for CRLF

---

ports/net-mgmt/aircrack-ng/Makefile.DragonFly
ports/net-mgmt/aircrack-ng/dragonfly/patch-scripts_Makefile

Does freebsd not have libpcap in base??

net-mgmt/aircrack-ng: Fix updated port

---

ports/misc/clex/dragonfly/patch-src_clexheaders.h
ports/net/belle-sip/dragonfly/patch-src_dns.c

Swildner pack part1, for upcoming POSIX namespace cleanup

Relax POSIX env as done on freebsd

---

ports/devel/R-cran-microbenchmark/dragonfly/patch-src_nanotimer.c
ports/www/R-cran-httpuv/dragonfly/patch-src_Makevars
ports/www/R-cran-httpuv/dragonfly/patch-src_libuv_common.gypi
ports/www/R-cran-httpuv/dragonfly/patch-src_libuv_src_unix_core.c
ports/www/R-cran-httpuv/dragonfly/patch-src_libuv_src_unix_fs.c
ports/www/R-cran-httpuv/dragonfly/patch-src_libuv_uv.gyp

httpuv: simple "echo" demo starts firefox with opened port
send message works
microbenchmark also seem to work but times seem to be *1000

Fix two last failing R-cran ports

---

ports/security/py-pow/dragonfly/patch-POW.c

For now just avoid compilation error.

security/py-pow: Fix build after openssl update on master.

---

ports/net/yate/Makefile.DragonFly

Mainly mutex _NP. Also add MAKE_JOBS_UNSAFE=yes

net/yate: Fix build.

---

ports/devel/clanlib/Makefile.DragonFly
ports/games/super_methane_brothers/dragonfly/patch-sources_misc.cpp

methane runs/plays/sounds great

devel/clanlib: Use alias and bundle a single game it has a dep on.

---

ports/games/iortcw/dragonfly/patch-MP_Makefile
ports/games/iortcw/dragonfly/patch-MP_code_qcommon_q__platform.h
ports/games/iortcw/dragonfly/patch-MP_code_zlib-1.2.8_ioapi.h
ports/games/iortcw/dragonfly/patch-SP_Makefile
ports/games/iortcw/dragonfly/patch-SP_code_qcommon_q__platform.h
ports/games/iortcw/dragonfly/patch-SP_code_zlib-1.2.8_ioapi.h

User request for irc.
Game requires pak0.pk3 to run from RTWC original CD that I don't own.

games/iortcw: Add DragonFly

---

ports/audio/audiere/dragonfly/patch-src_audiere.h
ports/devel/cherivis-devel/dragonfly/patch-CheriVis.mm
ports/devel/clanlib1/dragonfly/patch-Sources_API_Core_System_error.h
ports/devel/hadoop/dragonfly/patch-src_c++_utils_api_hadoop_SerialUtils.hh
ports/devel/hadoop2/dragonfly/patch-hadoop-tools_hadoop-pipes_src_main_native_utils_api_hadoop_SerialUtils.hh
ports/devel/log4cxx/dragonfly/patch-src_examples_cpp_console.cpp
ports/devel/love5/dragonfly/patch-src_opengl_ImageFont.h
ports/ftp/multiget/dragonfly/patch-batch.cpp
ports/ftp/multiget/dragonfly/patch-mgftpbase.h
ports/ftp/multiget/dragonfly/patch-mghttpbase.h
ports/games/glest/dragonfly/patch-source_shared__lib_sources_platform_posix_socket.cpp
ports/games/kartofel/dragonfly/patch-saved_game.cc
ports/irc/irc2dc/dragonfly/patch-src_defs.h
ports/lang/phc/dragonfly/patch-generated_ast.h
ports/mail/bbmail/dragonfly/patch-src_bbmail.cpp
ports/mail/bbmail/dragonfly/patch-src_mailboxmenu.cpp
ports/mail/bbmail/dragonfly/patch-src_main.cpp
ports/mail/bbmail/dragonfly/patch-src_resource.cpp
ports/net-p2p/bnbt/dragonfly/patch-bnbt.h
ports/sysutils/deltup/dragonfly/patch-file.h
ports/vietnamese/x-unikey/dragonfly/patch-src_ukengine_usrkeymap.cpp
ports/x11-toolkits/gtkmathview/dragonfly/patch-src_common_String.hh
ports/x11/metisse/dragonfly/patch-FvwmCompositor_desktop_MetisseWindow.H

<cstdio>: add missing include in ports

---

ports/devel/qbs/dragonfly/patch-src_lib_corelib_tools_processutils.cpp
ports/devel/qtcreator/Makefile.DragonFly

devel/qtcreator: Fix build blockers.

---

ports/x11/i3status/dragonfly/patch-src_print__cpu__usage.c

x11/i3status: Fix cpu_usage metric reporting.

---

ports/lang/f2c/dragonfly/patch-libf2c_MAIN.c

Move __weak_reference() below stub function.

lang/f2c: Adjust freebsd-ports patch.

---

ports/irc/iroffer-dinoex/dragonfly/patch-Configure
ports/irc/iroffer-dinoex/dragonfly/patch-src_dinoex__main.c
ports/irc/iroffer-dinoex/dragonfly/patch-src_iroffer__defines.h
ports/irc/iroffer-lamm/dragonfly/patch-Configure
ports/irc/iroffer-lamm/dragonfly/patch-src_iroffer__defines.h
ports/irc/iroffer-lamm/dragonfly/patch-src_iroffer__utilities.c
ports/irc/iroffer/dragonfly/patch-Configure
ports/irc/iroffer/dragonfly/patch-src_iroffer__defines.h
ports/irc/iroffer/dragonfly/patch-src_iroffer__utilities.c

Too simple to ignore even if packages quite old (2005)

irc/iroffer: Add DragonFly.

---

ports/textproc/openfts/dragonfly/patch-flexparser.l

textproc/openfts: Contra patch.

---

ports/games/osgg/dragonfly/patch-main.cpp

Game works, both graphics and sounds.

games/osgg: Fix patch.

---

ports/games/voxelands/Makefile.DragonFly
ports/games/voxelands/dragonfly/patch-src_porting.cpp

gcc5, gcc7 ICE @ -O2, while gcc6 even @ -O1.
For now just go with -O1 and hack through -lfreetype detection.
Game plays fine.

games/voxelands: Work around gcc issue + expand patches.

---

ports/lang/perl5.20/Makefile.DragonFly
ports/lang/perl5.22/Makefile.DragonFly

Use universal dfly-patch, me lazy ;)
smth with setproctitle("-%s", s);
Reported-by: Studbolt

lang/perl5-2.2{2,4}: Add patch like in perl.5.20.

---

ports/mail/spamd/Makefile.DragonFly
ports/mail/spamd/dragonfly/patch-spamd_sync.c
ports/mail/spamd/dragonfly/sha1hl_compat.h

Untested, other than synth test.
Requested-by: Studbolt

mail/spamd: Attempt to unbreak build.

---

ports/net/mtr/Makefile.DragonFly
ports/net/mtr/dragonfly/patch-mtr.c
ports/net/mtr/dragonfly/patch-net.c

While there, false out setcap(8).

net/mtr: Disable SCTP on DragonFly.

---

ports/devel/libopkele/Makefile.DragonFly
ports/devel/libopkele/dragonfly/patch-include_opkele_iterator.h
ports/devel/libopkele/dragonfly/patch-lib_curl.cc
ports/www/mod_auth_openid/Makefile.DragonFly

While there throw in fix for c++11 std and
add missing USES+=ssl in mod_auth_openid.

devel/libopkele: Fix and enable default base gcc.

---

ports/databases/postgis20/dragonfly/patch-raster_rt__core_rt__api.h

databases/postgis20: Fix strnicmp issue.

---

ports/www/ufdbguard/dragonfly/patch-src_mtserver_Makefile.in

www/ufdbguard: Hack object search.

---

ports/editors/teco/Makefile.DragonFly

Seems to be functional but i'm not sure how to do those *cmd$$

editors/teco: Fix build.

---

ports/ports-mgmt/pkg_cleanup/Makefile.DragonFly

Not sure if this one is useful or not but better than failure.

ports-mgmt/pkg_cleanup: Fix build, use ncurses.

---

ports/games/ascii-invaders/dragonfly/patch-Makefile

Game works nicely on 1080p terminal!!!

games/ascii-invaders: Fix build against ncurses.

---

ports/www/amphetadesk/diffs/Makefile.diff

Is -n 10 on purpose? creates dirs like:
drwxr-xr-x  3 meh  wheel  88 Dec 16 09:33 AmphetaDesk AmphetaDesk
Looks like -n 1 is enough for synth test

www/amphetadesk: Fix MF logic with xargs -n 10 -> 1

---

ports/x11/libfm-qt/dragonfly/patch-src_CMakeLists.txt

Two depending ports are also fine and will be brought in.

x11/libfm-qt: Install .pc file in correct location.

---

ports/graphics/appleseed/dragonfly/patch-CMakeLists.txt
ports/graphics/appleseed/dragonfly/patch-sandbox_stylesheets_default.qss
ports/graphics/appleseed/dragonfly/patch-src_appleseed.shared_application_application.cpp
ports/graphics/appleseed/dragonfly/patch-src_appleseed.studio_main_main.cpp
ports/graphics/appleseed/dragonfly/patch-src_appleseed_foundation_platform_path.cpp
ports/graphics/appleseed/dragonfly/patch-src_appleseed_foundation_platform_path.h
ports/graphics/appleseed/dragonfly/patch-src_appleseed_foundation_platform_snprintf_snprintf.cpp
ports/graphics/appleseed/dragonfly/patch-src_appleseed_foundation_platform_system.cpp
ports/graphics/appleseed/dragonfly/patch-src_appleseed_foundation_platform_thread.cpp
ports/graphics/appleseed/dragonfly/patch-src_appleseed_foundation_utility_log_logger.cpp

Both CLI ang GUI works, did some naughty things but works.
This requires openshadinglanguage that requires devel/llvm35 sadly.

graphics/appleseed: Add DragonFly.

---

ports/devel/babeltrace/Makefile.DragonFly

devel/babeltrace: Use alias

---

ports/devel/guikachu/Makefile.DragonFly
ports/devel/guikachu/dragonfly/patch-src_io_io-vfs.cc
ports/devel/guikachu/dragonfly/patch-src_property.cc
ports/devel/guikachu/dragonfly/patch-src_storage-node.cc

Also add missing depend on msgfmt.
Synth test only (gnome)

devel/guikachu: Fix c in not c.

---

ports/devel/libdsp/dragonfly/patch-Inlines-1.4.0_Alloc.hh

devel/libdsp: Fix c in not c

---

ports/devel/wxformbuilder/Makefile.DragonFly
ports/devel/wxformbuilder/dragonfly/patch-build_premake_4.3_src_host_premake.h
ports/devel/wxformbuilder/dragonfly/patch-create_build_files4.sh

devel/wxformbuilder: Add DragonFly

---

ports/graphics/yafray/Makefile.DragonFly
ports/graphics/yafray/dragonfly/patch-src_loader_mlex.cc
ports/graphics/yafray/dragonfly/patch-src_shaders_basictex.cc
ports/graphics/yafray/dragonfly/patch-src_yafraycore_HDR__io.cc
ports/graphics/yafray/dragonfly/patch-src_yafraycore_buffer.h
ports/graphics/yafray/dragonfly/patch-src_yafraycore_ccthreads.cc
ports/graphics/yafray/dragonfly/patch-src_yafraycore_geometree.h
ports/graphics/yafray/dragonfly/patch-src_yafraycore_kdtree.cc
ports/graphics/yafray/dragonfly/patch-src_yafraycore_renderblock.cc
ports/graphics/yafray/dragonfly/patch-src_yafraycore_targaIO.cc

CLI utility seems to work, but given its state make a good testcase.

graphics/yafray: Fix c in not c.

---

ports/math/z3/Makefile.DragonFly
ports/math/z3/dragonfly/patch-scripts_mk__util.py

Disable OpenMP for now.
CLI utility seems functional.

math/z3: Add DragonFly

---

ports/devel/pypersrc/dragonfly/patch-configure.sh
ports/devel/pypersrc/dragonfly/patch-tools_pythonconf.py

devel/pypersrc: Fix gmake detection.

---

ports/audio/muse/Makefile.DragonFly

audio/muse: Fix configure.

---

ports/audio/playgsf/Makefile.DragonFly

audio/playgsf: Remove bundled libresample.a

---

ports/devel/gdb/diffs/Makefile.diff
ports/devel/gdb/dragonfly/amd64dfly-nat.c
ports/devel/gdb/dragonfly/dfly-nat.c
ports/devel/gdb/dragonfly/extrapatch-kgdb
ports/devel/gdb/dragonfly/patch-gdb_Makefile.in
ports/devel/gdb/dragonfly/patch-gdb_osabi.c

For now stay back using non g++ build (__STDC macros and similar)

devel/gdb: Fix on new version.

---

ports/devel/e2fsprogs-libss/diffs/Makefile.diff

devel/e2fsprogs-libss: Try regened diffs

---

ports/security/heimdal/dragonfly/patch-cf_auth-modules.m4
ports/security/heimdal/dragonfly/patch-cf_pthreads.m4
ports/security/heimdal/dragonfly/patch-configure
ports/security/heimdal/dragonfly/patch-lib_kafs_Makefile.am
ports/security/heimdal/dragonfly/patch-lib_kafs_Makefile.in

Not that we need it but still.

security/heimdal: Fix build.

---

ports/www/firefox/dragonfly/patch-ipc_chromium_src_base_platform__thread__posix.cc
ports/www/firefox/dragonfly/patch-media_webrtc_trunk_webrtc_base_thread__checker__impl.cc

wwww/firefox: Add logic for <sys/lwp.h>

---

ports/mail/thunderbird/dragonfly/patch-mozilla_ipc_chromium_src_base_platform__thread__posix.cc
ports/mail/thunderbird/dragonfly/patch-mozilla_media_webrtc_trunk_webrtc_base_thread__checker__impl.cc
ports/www/seamonkey/dragonfly/patch-mozilla_ipc_chromium_src_base_platform__thread__posix.cc
ports/www/seamonkey/dragonfly/patch-mozilla_media_webrtc_trunk_webrtc_base_thread__checker__impl.cc

While there add one for thunderbird too.

www/seamonkey: Handle new <sys/lwp.h>

---

ports/devel/libdevq/Makefile.DragonFly

devel/libdevq: Adjust MD sed patch after update.

---

ports/sysutils/syslog-ng-devel/dragonfly/patch-lib_ivykis_src_iv__thread__posix.c
ports/sysutils/syslog-ng36/dragonfly/patch-lib_ivykis_src_iv__thread__posix.c
ports/sysutils/syslog-ng37/dragonfly/patch-lib_ivykis_src_iv__thread__posix.c

sysutils/syslog-ng*: Handle new <sys/lwp.h>

---

ports/www/squid/dragonfly/patch-src_CpuAffinitySet.cc

After CPU_* macros were added to base. We use do {...} while (0) for them.

www/squid: Fix build.

---

ports/benchmarks/flowgrind/Makefile.DragonFly
ports/benchmarks/flowgrind/dragonfly/patch-src_daemon.c
ports/devel/pecl-xhprof/Makefile.DragonFly
ports/devel/php-uprofiler/Makefile.DragonFly
ports/devel/umem/Makefile.DragonFly
ports/devel/umem/dragonfly/patch-umem.c
ports/devel/umem/dragonfly/patch-umem_fail.c
ports/net-mgmt/fastnetmon/Makefile.DragonFly
ports/net-mgmt/fastnetmon/dragonfly/patch-src_netmap__plugin_netmap__collector.cpp
ports/net/zmap/Makefile.DragonFly
ports/net/zmap/dragonfly/patch-CMakeLists.txt
ports/net/zmap/dragonfly/patch-lib_util.c
ports/net/zmap/dragonfly/patch-src_get__gateway.c
ports/net/zmap/dragonfly/patch-src_send.c
ports/sysutils/cpuid/Makefile.DragonFly

These now build and work after cpu_set_t additions.

Lift BROKEN from few ports.

---

ports/www/squid-devel/dragonfly/patch-src_CpuAffinitySet.cc
ports/www/squid-devel/dragonfly/patch-src_ssl_bio.cc
ports/www/squid-devel/dragonfly/patch-src_ssl_bio.h

same patch as non devel version

www/squid-devel: git add

---

ports/sysutils/py-psutil/dragonfly/patch-psutil___psutil__bsd.c
ports/sysutils/py-psutil/dragonfly/patch-psutil_arch_bsd_dragonfly.c

runtime issues.
* spyder (version 3.x) runs now fine.

Fix a couple of sysctls so psutil can be imported and does not have

---

ports/net/syncthing/dragonfly/patch-syscall_dragonfly.go

Taken from : https://github.com/golang/go/issues/20055

Fix build of syncthing

---

ports/devel/etcd/dragonfly/patch-Godeps___workspace_src_github.com_bgentry_speakeasy_speakeasy__unix.go
ports/devel/etcd/dragonfly/patch-storage_backend_boltoption__dragonfly.go

Fix devel/etcd build

---

ports/sysutils/packer/dragonfly/patch-packer_config__file__unix.go
ports/sysutils/packer/dragonfly/patch-vendor_github.com_bgentry_speakeasy_speakeasy__unix.go
ports/sysutils/packer/dragonfly/patch-vendor_github.com_mattn_go-isatty_isatty__bsd.go

This port is untested and it will potentially fail to work
properly but it's a start ;-)

sysutils/packer - Fix build

---

ports/devel/p5-Sys-CPU/dragonfly/patch-CPU.xs

While there bugfix CPU type retrieval for make test.

devel/p5-Sys-CPU: Add DragonFly handling.

---

ports/misc/rump/Makefile.DragonFly
ports/misc/rump/dragonfly/patch-src_sys_rump_net_lib_libshmif_shmif__user.c

- It builds fine, people might want to play with it :-)
- We will have to remove the specific patch in a version after
20180403 because we submited upstream to NetBSD a fix
(see PR misc/53153)

misc/rump: Revive

---

ports/devel/florist-gpl/dragonfly/patch-c-posix-signals.c
ports/dns/p5-Net-DNS-ToolKit/dragonfly/patch-siteconf
ports/mail/ifile/dragonfly

While there, add few missing signal names to florist-gpl.

Fix configure scripts in few ports.

---

ports/sysutils/u-boot-bananapi/Makefile.DragonFly
ports/sysutils/u-boot-bananapim2/Makefile.DragonFly
ports/sysutils/u-boot-beaglebone/Makefile.DragonFly
ports/sysutils/u-boot-cubieboard/Makefile.DragonFly
ports/sysutils/u-boot-cubieboard2/Makefile.DragonFly
ports/sysutils/u-boot-cubox-hummingboard/Makefile.DragonFly
ports/sysutils/u-boot-duovero/Makefile.DragonFly
ports/sysutils/u-boot-olimex-a20-som-evb/Makefile.DragonFly
ports/sysutils/u-boot-orangepi-one/Makefile.DragonFly
ports/sysutils/u-boot-pandaboard/Makefile.DragonFly
ports/sysutils/u-boot-pine64/Makefile.DragonFly
ports/sysutils/u-boot-rpi/Makefile.DragonFly
ports/sysutils/u-boot-rpi2/Makefile.DragonFly
ports/sysutils/u-boot-rpi3/Makefile.DragonFly
ports/sysutils/u-boot-sinovoip-bpi-m3/Makefile.DragonFly
ports/sysutils/u-boot-tools/Makefile.DragonFly
ports/sysutils/u-boot-utilite/Makefile.DragonFly
ports/sysutils/u-boot-wandboard/Makefile.DragonFly

Move ignore to sysutils/u-boot-tools (BUILD_DEPENDS).

Mask out u-boot images.

---

special/Mk/diffs/Uses_cmake.mk.diff
special/Mk/diffs/Uses_compiler.mk.diff
special/Mk/diffs/bsd.df.gcc.mk.diff
special/Mk/diffs/bsd.port.mk.diff

While there, add extra hook for late cmake args.

special: Add handling for gcc80.

---

ports/math/saga/diffs/Makefile.diff
ports/math/saga/dragonfly/patch-configure.ac
ports/math/saga/dragonfly/patch-src_tools_io_io__shapes__las_Makefile.am
ports/math/saga/dragonfly/patch-src_tools_io_io__shapes__las_Makefile.in
ports/math/saga/dragonfly/patch-src_tools_io_io__shapes__las_las__export.cpp
ports/math/saga/dragonfly/patch-src_tools_io_io__shapes__las_las__import.cpp
ports/math/saga/dragonfly/patch-src_tools_io_io__shapes__las_las__info.h

It should be broken in freebsd-ports too.

math/saga: Fix lib depend.

---

ports/games/powder-toy/dragonfly/patch-SConscript

Port useful for aggressive -O3 -ffast-math -funsafe-math-optimizations

games/powder-toy: Add DragonFly

---

ports/lang/rust/diffs/Makefile.diff
ports/lang/rust/dragonfly/patch-src_vendor_libgit2-sys_libgit2_src_openssl__stream.c
ports/lang/rust/dragonfly/patch-src_vendor_libgit2-sys_libgit2_src_openssl__stream.h
ports/lang/rust/dragonfly/patch-src_vendor_openssl-sys_build.rs
ports/lang/rust/dragonfly/patch-src_vendor_openssl-sys_src_lib.rs
ports/lang/rust/dragonfly/patch-src_vendor_openssl-sys_src_libressl_mod.rs
ports/lang/rust/dragonfly/patch-src_vendor_openssl-sys_src_ossl10x.rs
ports/lang/rust/dragonfly/patch-src_vendor_openssl-sys_src_ossl110.rs
ports/lang/rust/dragonfly/patch-src_vendor_openssl-sys_src_ossl111.rs

lang/rust: Add LibreSSL 2.7 support.

---

ports/www/obhttpd/Makefile.DragonFly
ports/www/obhttpd/dragonfly/patch-usr.sbin_httpd_Makefile

After the ifgroups functionality is available on master, this port builds and starts.

www/obhttpd: Port to DragonFly.

---

ports/net/vde2/dragonfly/patch-src_vde__plug2tap.c

net/vde2 - Fix build

---

ports/sysutils/beats/dragonfly/patch-src_github.com_elastic_beats_vendor_github.com_docker_docker_client_client__unix.go
ports/sysutils/beats/dragonfly/patch-src_github.com_elastic_beats_vendor_github.com_docker_docker_pkg_system_stat__dragonfly.go
ports/sysutils/beats/dragonfly/patch-vendor_github.com_tsg_gopacket_pcap_pcap.go

First attempt to bring a functional sysutils/beats to dports

sysutils/beats - Unbreak build

---

ports/lang/phantomjs/diffs/Makefile.diff
ports/lang/phantomjs/dragonfly/patch-src_qt_qtbase_configure
ports/lang/phantomjs/dragonfly/patch-src_qt_qtbase_src_corelib_io_qlockfile__unix.cpp
ports/lang/phantomjs/dragonfly/patch-src_qt_qtbase_src_network_ssl_qsslsocket__openssl__symbols.cpp
ports/lang/phantomjs/dragonfly/patch-src_qt_qtbase_src_network_ssl_qsslsocket__openssl__symbols__p.h

Added also a small diff against the Makefile which helps reducing the build log from 400M to 20M.

lang/phantomjs - Fix build

---

ports/graphics/weston/newport/Makefile
ports/graphics/weston/newport/pkg-plist

* Add install-strip, and wayland-backend.so to pkg-plist.

Fix weston build 2.

---

ports/devel/libevdev/newport/dragonfly/patch-tools_mouse-dpi-tool.c
ports/devel/libevdev/newport/dragonfly/patch-tools_touchpad-edge-detector.c

* I missed a few events in the last patch. The
mouse tool now works fine. The touchpad tool
I could not test, but at least the mainloop
is fine.

Fix the tools in devel/libevdev

---

ports/graphics/wayland/newport/files/patch-src_event-loop.c

* While there, make error messages a little more
fine grained.

Fix timer error in graphics/wayland

---

ports/net/zerotier/dragonfly/patch-osdep_BSDEthernetTap.cpp

Since revision 500708, DragonFly's tap(4) allows to set MTU > 1500, so
update the patch to support this.
In addition, fix the 'execl(ifconfig)' issue in the forked child
previously introduced by me to add DragonFly support.  Only one
'execl()' can be executed.

net/zerotier: Update patch for DragonFly revision 500708

---

ports/audio/din/Makefile.Dragonfly

Filter out freebsd specific libthr

audio/din : fix build

---

ports/ports-mgmt/pkg/dragonfly/df-latest.conf.sample

Remove duplicate and unavailable entries and sync with:
https://www.dragonflybsd.org/mirrors

ports-mgmt/pkg: Update repositories

---

ports/net-im/libnice/Makefile.DragonFly

There's probably a better way to do it...

net-im/libnice-gst1 : fix check-plist phase

---

ports/security/libfido2/dragonfly/patch-src_CMakeLists.txt
ports/security/libfido2/dragonfly/patch-src_hid_dragonfly.c

Basic attempt of copy/paste what exists for FreeBSD

security/libfido2 : fix configure phase

---

ports/www/node16/Makefile.DragonFly

Partially reverts commit 98b8bb933c89a7ca4de25d9e0dc306631702fbec

www/node16: Fix for 2022Q3

---

ports/comms/minicom/dragonfly/patch-src_minicom.c
ports/comms/minicom/dragonfly/patch-src_script.c

not sure about that one, but that makes it compile

comms/minicom : fix build phase

---

ports/net/samba412/dragonfly/patch-libcli_http_http.c

closes DragonFlyBSD/DPorts#233

net/samba412 : FreeBSD sscanf is also compatible with DragonFly

---

.github/workflows/github-actions-pullrequests.yml

Initial work to make Github Actions to build PRs for us.

Initial work to build PRs on dsynth

---

ports/archivers/rpm4/dragonfly/patch-misc_fts.c

archivers/rpm4: Fix patch phase

archivers/rpm4: Fix patch phase

---

ports/net/isc-dhcp44-server/dragonfly/patch-doc_examples_dhcpd-dhcpv6.conf

net/isc-dhcp44-server : fix default sample file dhcpd6.conf.sample

---

ports/lang/go-devel/diffs/distinfo.diff

lang/go-devel: Use newer bootstrap

lang/go-devel: Use newer bootstrap

---

ports/lang/go120/diffs/distinfo.diff
ports/lang/go120/dragonfly/patch-src_vendor_golang.org_x_net_route_interface__classic.go
ports/lang/go120/dragonfly/patch-src_vendor_golang.org_x_net_route_interface__dragonfly.go

lang/go120: Adapt patches and diffs

lang/go120: Adapt patches and diffs

---

ports/lang/go119/diffs/distinfo.diff

lang/go119: Fix fetch phase

---

ports/security/krb5-121/dragonfly/patch-config_shlib.conf
ports/security/krb5-121/dragonfly/patch-lib_crypto_builtin_aes_brg__endian.h
ports/security/krb5-121/dragonfly/patch-lib_rpc_svc__tcp.c
ports/security/krb5-121/dragonfly/patch-lib_rpc_svc__udp.c

That makes security/krb5 build.

security/krb5-121 : brings security/krb5-120 patches

---

ports/www/privoxy/dragonfly/patch-cgiedit.c

This patch has also been submitted to the upstream: https://sourceforge.net/p/ijbswa/bugs/940/

www/privoxy: Fix segfault error upon action editting in Web UI

---

ports/devel/sdl20/dragonfly/patch-src_joystick_linux_SDL__sysjoystick.c

devel/sdl20: Regen patch

---

ports/science/py-scipy/dragonfly/patch-scipy_spatial___ckdtree.pyx
ports/science/py-scipy/dragonfly/patch-scipy_special_wright.cc

Not sure if `INFINITY` is ok to import. Please check if possible.

science/py-scipy: Regen patches

---

ports/devel/grpc/dragonfly/patch-src_core_lib_gprpp_posix_directory__reader.cc

Fixes missing MakeDirectoryReader symbol

devel/grpc: Fix missing symbol

---

ports/www/yarn-node20/diffs/Makefile.diff

Fix https://github.com/DragonFlyBSD/DPorts/issues/258

www/yarn-node20: Tweak Makefile to port to DragonFly
